### ISSUE TITLE
Error occurred when trying MusicBrainz lookup

### ISSUE THREAD

**Issue by plsng** [quodlibet/quodlibet#1606] opened 2015-05-06 18:57 UTC
=== SYSTEM INFORMATION:
Quod Libet 3.4.0
Mutagen 1.22
Python 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC] linux2
Platform Linux-3.17.2-1-desktop-x86_64-with-SuSE-13.2-x86_64

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/songsmenu.py", line 182, in __on_activate
    self.__handle(item, plugin, library, songs, parent)

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/songsmenu.py", line 225, in __handle
    parent, plugin.PLUGIN_NAME, total):

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/songsmenu.py", line 80, in confirm
    resp = cls(parent, plugin_name, count).run()

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/songsmenu.py", line 63, in __init__
    count) % (plugin_name, count)

TypeError: format requires a mapping

=== LOG:
D: 294.02: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 294.02: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 294.02: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 294.13: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 294.31: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 294.36: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 294.40: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 294.44: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 295.35: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 295.47: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 296.50: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 296.56: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 298.68: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 298.79: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7deababb90 (quodlibet+qltk+completion+LibraryValueCompletion at 0x9652530)>>
D: 304.20: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 304.20: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 304.20: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 304.32: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 304.59: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 304.63: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 304.65: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 304.70: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30fa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 305.52: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 305.62: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de9d30140 (quodlibet+qltk+completion+LibraryValueCompletion at 0x967ddb0)>>
D: 312.64: SongFileLibrary._changed: Changing 4 items.
D: 312.64: qltk.completion.__update_song: Updating tag model for 4 songs
D: 312.64: qltk.completion.__update_song: Done updating tag model for 4 songs
D: 312.65: library.libraries.__changed: Updating affected albums for 4 items
D: 316.59: qltk.window.__restore_state: Restore state
D: 316.59: qltk.window.__restore_position: Restore position
D: 316.59: qltk.window.__restore_size: Restore size
D: 318.39: PlaylistModel.set: Clearing model.
D: 318.39: PlaylistModel.set: Setting 22 songs.
D: 318.39: PlaylistModel.set: Done filling model.
D: 348.89: SongFileLibrary._changed: Changing 8 items.
D: 348.89: qltk.completion.__update_song: Updating tag model for 8 songs
D: 348.89: qltk.completion.__update_song: Done updating tag model for 8 songs
D: 348.89: library.libraries.__changed: Updating affected albums for 8 items
D: 351.38: qltk.window.__restore_state: Restore state
D: 351.38: qltk.window.__restore_position: Restore position
D: 351.38: qltk.window.__restore_size: Restore size
D: 363.01: SongFileLibrary._changed: Changing 18 items.
D: 363.01: qltk.completion.__update_song: Updating tag model for 18 songs
D: 363.01: qltk.completion.__update_song: Done updating tag model for 18 songs
D: 363.03: library.libraries.__changed: Updating affected albums for 18 items
D: 364.23: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 364.23: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 364.23: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 364.34: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 365.02: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 365.08: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 365.11: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c280 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c280 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 365.16: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c280 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 365.80: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 365.90: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f7de924c370 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8e986b0)>>
D: 370.20: SongFileLibrary._changed: Changing 18 items.
D: 370.20: qltk.completion.__update_song: Updating tag model for 18 songs
D: 370.20: qltk.completion.__update_song: Done updating tag model for 18 songs
D: 370.21: library.libraries.__changed: Updating affected albums for 18 items
D: 372.06: qltk.window.__restore_state: Restore state
D: 372.06: qltk.window.__restore_position: Restore position
D: 372.06: qltk.window.__restore_size: Restore size
D: 387.32: PlaylistModel.set: Clearing model.
D: 387.32: PlaylistModel.set: Setting 7 songs.
D: 387.33: PlaylistModel.set: Done filling model.
D: 390.30: PlaylistModel.set: Clearing model.
D: 390.30: PlaylistModel.set: Setting 356 songs.
D: 390.31: PlaylistModel.set: Done filling model.
D: 392.69: SongFileLibrary._changed: Changing 4 items.
D: 392.70: qltk.completion.__update_song: Updating tag model for 4 songs
D: 392.70: qltk.completion.__update_song: Done updating tag model for 4 songs
D: 392.70: library.libraries.__changed: Updating affected albums for 4 items
D: 392.75: PlaylistModel.set: Clearing model.
D: 392.75: PlaylistModel.set: Setting 356 songs.
D: 392.76: PlaylistModel.set: Done filling model.

**Comment by declension** [comment] 2015-05-11 08:15
Thanks. This is most probably a duplicate of #1578, and should have been fixed now in revision ccf8a9de283054aedd353281c6cec542125d624d. 

Please try upgrading to latest unstable, and re-open if this doesn't fix it.

**Closed** 2015-05-11 08:16 UTC
Labels: bug, duplicate
