### ISSUE TITLE
Stop-after as a right-click option in the queue / playlist / current search

### ISSUE THREAD

**Issue by Jimi-James** [quodlibet/quodlibet#3837] opened 2021-11-05 18:51 UTC
The proposed change
-------------------
Way back when I used Clementine, this was a feature on it. You could pick any song in the queue and flag it so that when it gets to and finishes playing that song, it then stops playback.

Benefits of this change
-----------------------
As I get into not exclusively using my queue, and mixing it with things like shuffle mode per setting/schedule/mood, I'm finding this feature would be appreciated.

This is by no means that big a deal, but it would be nice. Very low priority, I suppose.

Any issues this might cause
---------------------------
Not sure what if any issues this feature could cause. It probably doesn't have to use custom ex falso tags have such a flag on a song, though if it did then that may open its own minor can of worms.

**Comment by j1warren** [comment] 2021-11-28 12:36
This would also fix #3710

**Comment by dorsiflexion** [comment] 2022-02-11 23:02
This sounds like a duplicate of #678.

**Comment by declension** [comment] 2022-02-12 12:31
Thanks. Closing in favour of #678

**Closed by declension** 2022-02-12 12:31 UTC
Labels: enhancement, plugins, player
