### ISSUE TITLE
Sorting within album does not work properly

### ISSUE THREAD

**Issue by CAtoDC** [quodlibet/quodlibet#4094] opened 2022-08-14 17:08 UTC
Steps to reproduce
------------------

Clicking on Track does not toggle ascending / descending.

Expected Output
---------------

It should toggle based on tracknumber.

Actual Output
-------------

The sort is out of order.

Test System
-----------

### Which version of Quod Libet?

v4.5.0

### Which operating system 

Pop_OS 22.04 and also Windows 10

### If it's audio-related, what back-end?

Additional Information
----------------------

![quod_libet_sorting](https://user-images.githubusercontent.com/8337820/184547547-e40cc1fd-09ed-4b23-b551-7df1cf419318.png)

**Comment by declension** [comment] 2022-08-14 17:36
I can't replicate this (on latest). Can you give a bit more information:

* which browser are you using here?
* What format audio files are these?
* What are the tags (in particular `tracknumber` etc set to? (a few examples will do). You can use `operon list $FILENAME` and paste here..

**Comment by CAtoDC** [comment] 2022-08-15 02:16
Hi Nick.

The audio format is FLAC.  The tag that I expect to sort is
tracknumber (these typically have two digit numbers 01, 02, etc.).

I'm not sure what you're asking for with the browser information. If you
mean web browser, then Google Chrome.

I've seen this issue on both my Win 10 machine and on my Linux laptop (Pop
OS 22.04).

Thanks!

**Comment by declension** [comment] 2022-08-15 08:12
Thanks

> The tag that I expect to sort is tracknumber (these typically have two digit numbers 01, 02, etc.). 
Great - if you can dump the values from the tags (`operon list $SOME_FILE.flac`)  as above then we can see what's going on

> I'm not sure what you're asking for with the browser information. 

I meant which [QL browser](https://quodlibet.readthedocs.io/en/latest/guide/browse/index.html) - Track List / Playlists / Album List etc

**Comment by KarimbaYo** [comment] 2022-08-15 21:36
Hi,
I think I've seen this problem before.
As I recall, this happens when some tags aren't exactly the same throughout the album, typically when the files come from different sources.
Sometimes it's just a space or a capital letter in the album name (or albumartist or musicbrainz_albumid or labelid, I can't remember).
Are all these tags common to the whole album really identical?

**Comment by CAtoDC** [comment] 2022-08-16 01:46
That actually makes sense. The album I was looking at had one song from a
separate album - and it was that one that wouldn't sort properly.

A similar thing happens in my Playlists. They don't stay in the order I put
them in.

**Comment by declension** [comment] 2022-09-18 19:56
From what I can tell here, this is QL working as intended. Can we close this then?

**Comment by declension** [comment] 2024-01-17 20:00
Closing for now then

**Closed by declension** 2024-01-17 20:00 UTC
Labels: bug
