### ISSUE TITLE
Error after open Ex Falso Preferences

### ISSUE THREAD

**Issue by Anifyuli** [quodlibet/quodlibet#4038] opened 2022-07-06 13:22 UTC
Steps to reproduce
------------------

Open Ex Falso Preferances menu

Expected Output
---------------

Not showing a problem and Ex Falso Preferences can to open

Actual Output
-------------

Showing error and confuse what should I do

Test System
-----------

### Which version of Quod Libet?

4.4.0
### Which operating system 

Pop! OS 22.04 based Ubuntu 22.04 LTS Jammy Jellyfish

### If it's audio-related, what back-end?

Not understand and don't know

Additional Information
----------------------

![image](https://user-images.githubusercontent.com/73734843/177560003-b695a666-73ef-4666-aba8-be83940dce1e.png)

**Comment by declension** [comment] 2022-07-16 13:19
Thanks for the report. This is fixed in QL 4.5.0.

Closing as duplicate of #3608

**Closed by declension** 2022-07-16 13:19 UTC
Labels: bug
