### ISSUE TITLE
CI: msys2 build is broken

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3457] opened 2020-10-05 07:31 UTC
Steps to reproduce
------------------
Run CI a few times

Expected Output
---------------
No unexpected errors 

Actual Output
-------------
msys2 job consistently fails. First failure was [build 1206180223](https://github.com/quodlibet/quodlibet/runs/1206180223?check_suite_focus=true).
Lots of connection errors followed by: 
```
 error: mingw-w64-x86_64-libunistring: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is invalid
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-libunistring-0.9.10-2-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: failed to commit transaction (invalid or corrupted package)
Do you want to delete it? [Y/n] 
```

**Comment by lazka** [comment] 2020-10-05 07:49
yeah, the server is dead right now...

**Comment by galgalesh** [comment] 2020-10-05 11:07
I'm seeing the same issue when installing packages. Is this caused by the problems with the primary repository? Is there a way to workaround this?

**Comment by lazka** [comment] 2020-10-05 13:14
The signature thing is fixed now (the sf mirror had an outdated file) and since we are using the github action now we just hit the cache and not the real server.

**Closed by lazka** 2020-10-05 13:14 UTC
Labels: CI, bug, windows
