### ISSUE TITLE
Songs are forcibly removed from playlist on refresh

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1010] opened 2015-03-14 23:57 UTC
Original [issue 1010](https://code.google.com/p/quodlibet/issues/detail?id=1010) created by _deepfire@feelingofgreen.ru on 2012-07-20T10:30:02.000Z:

This applies to all versions of QL, up to, at least 2.2.1.

The misbehaviour can be summarised as the general QL's policy of dropping an entry from a playlist, whenever it is unable to locate the corresponding file.

While this could be desirable for some people, there are others, who absolutely loathe this.

This is aggravated by the fact, that sometimes QL fails to locate the file, despite it being present -- which leads to gratuitious lossage.

The proposed solution is to provide an optional mode, whereby playlist entries for missing files will not be deleted, but rather presented as such.

**Comment by CreamyCookie** [comment] 2019-06-21 21:02
Duplicate of #1733 as far as I can see.

**Closed by CreamyCookie** 2019-06-21 21:02 UTC
Labels: bug
