### ISSUE TITLE
[Song Notifications plugin] cover.jpg is not used for songs that don't have embedded art

### ISSUE THREAD

**Issue by shishess** [quodlibet/quodlibet#2150] opened 2016-12-18 19:31 UTC
The Song Notifications plugin doesn't use (e.g.) cover.jpg for song files that don't have embedded art.

In addition, if you switch from playing a song that includes embedded art to one that doesn't before the first notification goes away, the embedded art for the first song will be shown in the notification for the second song.

**Comment by lazka** [comment] 2016-12-18 19:35
Which desktop environment are you using? And which version of quod libet?

**Comment by shishess** [comment] 2016-12-18 19:50
Mate Desktop

Quod Libet 3.7.1

**Comment by lazka** [comment] 2016-12-18 20:17
Thanks. One more thing: does the cover.jpg show correctly in quodlibet itself?

**Comment by shishess** [comment] 2016-12-18 21:01
Yes, the cover.jpg shows in Quod Libet itself, as well as in the Animated On-Screen Display plugin.

**Comment by lazka** [comment] 2016-12-18 21:02
Thanks. I'll need to test with mate since I can't reproduce the issue with gnome-shell.

**Comment by lazka** [comment] 2016-12-19 18:58
This is a mate-desktop-notification-daemon bug.

Looking at strace it correctly receives the URI but fails to unescape spaces. This doesn't happen with embedded images since we temporarily safe them under /tmp with a path without spaces.

**Comment by lazka** [comment] 2016-12-19 19:05
Filed upstream: https://github.com/mate-desktop/mate-notification-daemon/issues/117

**Comment by jmccrohan** [comment] 2017-02-09 22:54
@lazka 

I also encountered this issue when using Awesome WM. I've submitted a PR to resolve the issue.

How about extending the embedded images plugin so that album art found in filesystem folders can be served in the same way as embedded album art?

An advantage of this method would be to allow the images to be resized to a consistent size before being passed to the notification daemon.

**Comment by lazka** [comment] 2017-02-10 06:28
> I also encountered this issue when using Awesome WM. I've submitted a PR to resolve the issue.

Thanks. -> https://github.com/awesomeWM/awesome/pull/1536

> How about extending the embedded images plugin so that album art found in filesystem folders can be served in the same way as embedded album art?

In both cases we send a path to a local image file. What do you mean?

**Comment by lazka** [comment] 2017-05-07 12:21
The mate bug still seems unfixed, but there isn't much we can do here, so closing.

**Closed by lazka** 2017-05-07 12:21 UTC
Labels: bug, forwarded-upstream, upstream-bug

**Comment by lazka** [comment] 2017-10-25 10:24
(This was just marked as fixed in mate)
