### ISSUE TITLE
[Error] TypeError: validate_object_path() argument 1 must be string, not None

### ISSUE THREAD

**Issue by chartreusrav95** [quodlibet/quodlibet#2941] opened 2018-08-19 08:57 UTC
* What did you try to do when the error occurred?

Error Details:
```
Traceback (most recent call last):

  File "/usr/bin/exfalso", line 15, in <module>
    sys.exit(main())

  File "/usr/lib/python2.7/dist-packages/quodlibet/exfalso.py", line 63, in main
    session.init("exfalso")

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/session.py", line 29, in init
    client = bus.get_object("org.gnome.SessionManager", client_path)

  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)

  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 244, in __init__
    _dbus_bindings.validate_object_path(object_path)

TypeError: validate_object_path() argument 1 must be string, not None


Version: 3.9.1
Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
Platform: Linux-4.15.0-32-generic-x86_64-with-Ubuntu-18.04-bionic
```

**Comment by qarkai** [comment] 2018-08-20 14:03
Duplicate of #2759.

**Closed by qarkai** 2018-08-20 14:03 UTC
