### ISSUE TITLE
Ratings are not saved in tags

### ISSUE THREAD

**Issue by BraveSentry** [quodlibet/quodlibet#3566] opened 2021-02-21 18:59 UTC
Steps to reproduce
------------------
- Check the box in Preferences -> Tags -> Save ratings and play counts in tags
- Entered a valid email address.
- Set a rating for a song.
- Run plugin "Export metadata"

Expected Output
---------------
- The rating should be shown in the *.tags file.
- The rating should be visible in other software and/or a different QL install.

Actual Output
-------------
The rating is not shown in the *.tags file and not visible in other software.

Test System
-----------

### Which version of Quod Libet?
4.4 on Linux Mint 20.1
4.3 on MacOS 10.15.7

**Comment by declension** [comment] 2021-02-27 10:20
Thanks. Are we saying this is a bug with the tag export plugin or a bug in the library ratings saving (in which case we'd need more details about that bit)

**Comment by BraveSentry** [comment] 2021-03-01 05:52
I have no idea, but would be happy to provide any details you need.

**Comment by CreamyCookie** [comment] 2021-03-01 15:55
I think this is very very likely a duplicate of #1852 - If I'm mistaken, feel free to reopen, or comment here if there's more information that contradicts the following!

The [import / export plugin](https://github.com/quodlibet/quodlibet/blob/0bf94feaffe8f10a007c053d3aa0b49c944059e8/quodlibet/ext/songsmenu/importexport.py) does export every tag. It's just that "Save ratings and play counts in tags" is a bit unintuitive in that ratings are only saved in tags if you actually trigger it via the "Update Tags in Files" or the "Auto Update Tags in Files" plugin, and even then only if the format supports it (opus, ogg, flac, mp3, I think).

**Closed by CreamyCookie** 2021-03-01 15:55 UTC
Labels: bug
