### ISSUE TITLE
[Error] FaultHandlerCrash: Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by sierra-js** [quodlibet/quodlibet#2990] opened 2018-10-09 00:28 UTC
* What did you try to do when the error occurred?
FLAC file playback.
Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/quodlibet/errorreport/faulthandling.py", line 137, in raise_and_clear_error
    raise FaultHandlerCrash(text)

FaultHandlerCrash: Fatal Python error: Segmentation fault

Stack (most recent call first):
  File "/usr/lib/python2.7/site-packages/quodlibet/util/picklehelper.py", line 38 in pickle_dumps
  File "/usr/lib/python2.7/site-packages/quodlibet/formats/_serialize.py", line 213 in dump_audio_files
  File "/usr/lib/python2.7/site-packages/quodlibet/library/libraries.py", line 272 in save
  File "/usr/lib/python2.7/site-packages/quodlibet/library/__init__.py", line 55 in save
  File "/usr/lib/python2.7/site-packages/quodlibet/_main.py", line 363 in periodic_library_save
  File "/usr/lib/python2.7/site-packages/quodlibet/util/copool.py", line 25 in wrap
  File "/usr/lib/python2.7/site-packages/quodlibet/_main.py", line 338 in run
  File "/usr/lib/python2.7/site-packages/quodlibet/main.py", line 193 in main
  File "/usr/bin/quodlibet", line 14 in <module>


Version: 3.9.1
Python: 2.7.15 (default, May  9 2018, 11:32:33) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
Platform: Linux-4.16.11-100.fc26.x86_64-x86_64-with-fedora-26-Bloat
```

**Comment by CreamyCookie** [comment] 2019-07-24 09:52
Closing this as a duplicate of  #2831

**Comment by declension** [comment] 2021-04-05 15:39
Too old to replicate, closing

**Closed by declension** 2021-04-05 15:39 UTC
