### ISSUE TITLE
Edit Playcount plugin causes files to be modified on disk

### ISSUE THREAD

**Issue by everdred** [quodlibet/quodlibet#3421] opened 2020-08-02 04:35 UTC
Steps to reproduce
------------------
1. Use "Edit playcount" plugin to modify a song's play or skip count.
2. Observe that file modification date has been updated. 
(Note: I have QL preference "Save ratings and play counts in tags" disabled.)

Expected Output
---------------
File should not be modified, respecting application's "Save ratings and play counts in tags" setting.

Actual Output
-------------
File is modified.

Test System
-----------

### Which version of Quod Libet?
4.3.0.0~ppa0~quodlibet~stable

### Which operating system 
Debian Testing

**Comment by CreamyCookie** [comment] 2020-09-04 12:12
This is a duplicate of #2483.

Still, thank you for reporting it!

**Closed by CreamyCookie** 2020-09-04 12:12 UTC
Labels: bug
