### ISSUE TITLE
Cyclic queue save; Restore song on start not in the song list

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1358] opened 2015-03-15 00:45 UTC
Original [issue 1358](https://code.google.com/p/quodlibet/issues/detail?id=1358) created by kalvin.rubiksmaster on 2014-04-01T03:07:32.000Z:

As of now, the file which notes the queue contents (for me, ~/.quodlibet/queue) seems only to be written once per run: at the very end, when one exits QuodLibet. 

If QuodLibet is forcibly killed for any reason (e.g. complete system crash), the queue file is not written, and the user is faced with a queue state that's really, really old when QuodLibet next starts. 

For example, imagine my queue (upon start-up) is 

song1
song2
song5
song6
song8

Let's say I completely empty my queue and enqueue some entirely different pieces such that the queue now looks like

song99
song88
song55

Imagine now that inexplicably and unfortunately, QuodLibet crashes without a chance to clean up or do exit writes. After some panicking (and probably rebooting), I restart QuodLibet. Gone or songs 99, 88, and 55 from the queue - instead, the initial five-song queue is back in place. 

I'm not proposing anything, but just curious if this would be easy to implement (because if it is, I might have a crack at it myself): might one somehow modify the output of &quot;quodlibet --print-queue&quot; and redirect it to the queue file? The single difficulty is the output prepending file:/// to every item in the queue and treating special characters the funny way. 

This to me would be more user-friendly than quitting and restarting QuodLibet every time I want to see my queue written (just in case. Bad things do happen every now and then on my personal system). 

There are some miscellaneous queue idiosyncrasies I'd like to note; these are probably less bugs and more oddities not completely covered in the documentation? 
- Move the album selector to some album, any album. Then play a song NOT in that album. While this song is playing, quit QL. Now start QL again. The &quot;now playing&quot; field is now blank; QL does not recall playing any song before it quit. This behavior is not observed when the album selector is set to &quot;All Albums.&quot; 
- Play a song, and while playing said song put it somewhere in your queue (doesn't matter where). Quit QL. Now start QL again. While the &quot;now playing&quot; state is correct (barring the above case, it remembers the song and how long it was playing), the first queued instance of the same song is now gone from the queue. Imagine the following: 

now playing: song5

queue: song1, song2, song3, song4, song5, song6, song7, song5, song5, song5

/\* Quit. Restart. */

now playing: song5

queue: song1, song2, song3, song4, song6, song7, song5, song5, song5

Just a little curious.

**Comment by Jimi-James** [comment] 2018-01-28 07:56
I'd actually love to see this get implemented. You might remember when I was asking for help with various things around doing the --print-queue method that HiKaPh mentioned. After upgrading to quodlibet 4, about 80% of the functionality in my wrapper script just stopped working. Some of the issues have *nothing* to do with quodlibet and are as if they're bugs in Bash itself, despite being caused by the upgrade. I remember when I was first making the script, I had to deal with several bugs that were just as bizarre for the same reasons, and I'm not interested in doing that again. Meanwhile, quodlibet has gotten so much more robust at everything (especially remembering the currently playing song, even if it crashes) since I first started using that script. Having a queue that saves to $HOME/.quodlibet/queue every time it changes, rather than just when the program exits, is all I need to never miss that script again.

**Comment by j39m** [comment] 2019-02-10 02:35
Jimi-James, this is `hikaph` (under yet another name) - I wrote [my own script](https://github.com/j39m/qlqw/) (probably similar to yours) in Python. I haven't actually fallen back on it in a long time (I had a bad time with GStreamer at one point but nothing recently), but I do still run it as a security blanket.

**Comment by bassstorm** [comment] 2021-04-24 19:30
Closing this ticket as it is partially fixed and more clean #3649 is created for the rest.

**Closed by bassstorm** 2021-04-24 19:30 UTC
Labels: enhancement
