### ISSUE TITLE
quodlibet-4.6.0 doesn't work with MacOSX Sonoma

### ISSUE THREAD

**Issue by popeyebrown** [quodlibet/quodlibet#4385] opened 2023-10-04 19:26 UTC
Steps to reproduce
------------------

Expected Output
---------------

Actual Output
-------------

Test System
-----------

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by popeyebrown** [comment] 2023-10-04 19:28
i Have tried running Quodlibet-4.6.0 with its dependences.  but i am stumped!    Heres the code.  

joe@OscarII ~ % quodlibet 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/quodlibet", line 11, in <module>
    from quodlibet.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/quodlibet/__init__.py", line 21, in <module>
    from .util.i18n import _, C_, N_, ngettext, npgettext
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/quodlibet/util/__init__.py", line 39, in <module>
    from .i18n import _, C_
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/quodlibet/util/i18n.py", line 15, in <module>
    from quodlibet.util.path import unexpand, xdg_get_system_data_dirs
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/quodlibet/util/path.py", line 29, in <module>
    from Foundation import NSString
ModuleNotFoundError: No module named 'Foundation'
joe@OscarII ~ %

**Comment by jdykstra** [comment] 2023-10-10 13:41
You're missing PyObjC.

Duplicate of [https://github.com/quodlibet/quodlibet/issues/4384].

**Comment by jdykstra** [comment] 2023-10-22 16:08
Current status:  Cannot build gettext-0.21.1 due to:

`libtool: link: /Applications/Xcode.app/Contents/Developer/usr/bin/gcc -dynamiclib  -o .libs/libtextstyle.0.dylib  .libs/gl_array_list.o .libs/basename-lgpl.o .libs/binary-io.o .libs/c-ctype.o .libs/c-strcasecmp.o .libs/c-strncasecmp.o .libs/cloexec.o .libs/concat-filename.o .libs/exitfail.o .libs/fatal-signal.o .libs/fd-hook.o .libs/fd-ostream.o .libs/file-ostream.o .libs/full-write.o .libs/get_ppid_of.o .libs/get_progname_of.o .libs/getprogname.o .libs/html-ostream.o .libs/html-styled-ostream.o .libs/ialloc.o .libs/iconv-ostream.o .libs/gl_list.o glthread/.libs/lock.o .libs/malloca.o .libs/math.o .libs/mem-hash-map.o .libs/memory-ostream.o .libs/noop-styled-ostream.o .libs/ostream.o .libs/printf-frexp.o .libs/printf-frexpl.o .libs/safe-read.o .libs/safe-write.o .libs/sig-handler.o .libs/sockets.o .libs/stat-time.o .libs/styled-ostream.o .libs/sys_socket.o .libs/term-ostream.o .libs/term-style-control.o .libs/term-styled-ostream.o glthread/.libs/threadlib.o .libs/unistd.o unistr/.libs/u8-mbtouc.o unistr/.libs/u8-mbtouc-aux.o .libs/xmalloc.o .libs/xalloc-die.o .libs/xconcat-filename.o .libs/xgethostname.o .libs/gl_xlist.o .libs/xsize.o .libs/xvasprintf.o .libs/xasprintf.o .libs/color.o .libs/misc.o .libs/version.o .libs/asnprintf.o .libs/asprintf.o .libs/error.o .libs/free.o .libs/obstack.o .libs/open.o .libs/printf-args.o .libs/printf-parse.o .libs/reallocarray.o .libs/snprintf.o .libs/stat.o .libs/strerror.o .libs/strerror-override.o .libs/vasnprintf.o .libs/vasprintf.o   -Wl,-force_load,./.libs/libcroco_rpl.a -Wl,-force_load,./.libs/libglib_rpl.a -Wl,-force_load,./.libs/libxml_rpl.a  -lncurses -L/Users/jwd/nobackup-cs/ql_bundle_build/quodlibet/dev-utils/osx_bundle/_home/jhbuild_prefix/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib -L/Users/jwd/.pyenv/versions/3.11.6/lib  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-headerpad_max_install_names   -install_name  /Users/jwd/nobackup-cs/ql_bundle_build/quodlibet/dev-utils/osx_bundle/_home/jhbuild_prefix/lib/libtextstyle.0.dylib -compatibility_version 2 -current_version 2.2 -Wl,-exported_symbols_list,.libs/libtextstyle-symbols.expsym
ld: Undefined symbols:
  _iconv_ostream_create, referenced from:
      <initial-undefines>
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [libtextstyle.la] Error 1
make[4]: *** [all] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
*** Error during phase build of gettext: ########## Error running make -j 17  *** [9/16]`

iconv_ostream_create() is not being built because of autotools config option HAVE_ICONV.  The reference is from a ld -u option created by libtool.  Currently figuring out which is wrong.  Remainder of python build dependencies look fine.

**Comment by declension** [comment] 2023-12-01 21:07
Closing as duplicate

**Closed by declension** 2023-12-01 21:07 UTC
Labels: bug
