### ISSUE TITLE
Editing features are disabled when editing tags on KDE

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#2235] opened 2017-02-12 18:03 UTC
Steps to reproduce:

1. Press Alt-Enter in order to see the tags of a song
1. I double click the value of a tag in order to edit it
1. I cannot select any text to copy it to the clipboard, by using the mouse or the keyboard.

It doesn't behave like a regular text edit field.

**Comment by pschwede** [comment] 2017-02-12 20:30
Thanks, I didn't know about [Alt]+[Enter] :+1:

However, I cannot reproduce your problem in QL 3.9 (dev) but can copy/paste things normally.

**Comment by DavidPerezIngeniero** [comment] 2017-02-12 20:33
I'm using Linux, KDE Neon 4.9.1 and QL 3.8.1

**Comment by declension** [comment] 2017-02-13 09:22
I can't reproduce this either (on Ubuntu with GTK+ 3.20.9). 

Sounds like this is probably a KDE-specific issue.

**Comment by DavidPerezIngeniero** [comment] 2017-02-13 15:11
If necessary, I can provide the song.

**Comment by DavidPerezIngeniero** [comment] 2017-02-13 15:12
It's strange, it is the only app I have installed in my computer with this problem in a text field.  The search field works ok.

**Comment by lazka** [comment] 2017-03-06 12:52
I can't reproduce with plasma from arch.

**Comment by DavidPerezIngeniero** [comment] 2017-03-07 11:39
Strange.  KDE Neon must have little bugs, as this is the distro that KDE developers use more on a daily basis.

**Comment by DavidPerezIngeniero** [comment] 2017-03-07 11:41
Tried with OpenSuse Leap 42.1 in a Plasma desktop and it works.

**Comment by lazka** [comment] 2017-03-07 11:42
Maybe a theme issue? Try selecting a different theme using the theme switcher plugin in QL.

**Comment by CreamyCookie** [comment] 2019-07-26 15:18
@DavidPerezIngeniero Is this still an issue? Can't reproduce here either. (Kubuntu 18.04)

**Comment by CreamyCookie** [comment] 2019-08-13 12:45
Closing this for now as `Can't reproduce`. Feel free to comment here if the issue re-appears in the latest version.

**Closed by CreamyCookie** 2019-08-13 12:45 UTC
Labels: bug, needinfo
