### ISSUE TITLE
Feature request: cursor follows playpack option

### ISSUE THREAD

**Issue by D759** [quodlibet/quodlibet#1809] opened 2016-02-04 22:02 UTC
it would be nice to have an option that the cursor follows the currently paying track.

Currently using QuodLibet on OS X 10.11

**Comment by lazka** [comment] 2016-02-05 05:57
Could you be more specific?

**Comment by D759** [comment] 2016-02-05 18:13
Sure. 
When I doubleclick a song in the playlist view to play it, the line is marked blue (= "cursor") the playback indicator is the little play symbol on the left. Now when the song starts to play, the "cursor" stays where it was. (see attached screenshot: I clicked track 4 to play, playback moves to track 5, but the "cursor" stays on track 4) 
I would like it to automatically jump the marking to the currently playing song.

(sorry if not clear, this is an option i am used to from foobar2000 where it is called "cursor follows playback")

<img width="1043" alt="bildschirmfoto 2016-02-05 um 19 04 10" src="https://cloud.githubusercontent.com/assets/17073878/12854681/47c42d1e-cc3b-11e5-820d-ea9fcef4b0de.png">

**Comment by urielz** [comment] 2016-02-05 20:16
If this gets implemented it should be implement as an option in my opinion. At least in my case that is not the way I use the cursor. For example one I add a new album I often listen to it while I edit the metadata of songs, having the cursor jump to the current song being played would disrupt that process...

**Comment by lazka** [comment] 2016-02-05 20:26
@D759 I see, thanks. Why do you want that feature? Note that QL scrolls to the playing song when manually initiating a song change and provides a shortcut (ctrl+j) to jump to it.

I agree with @urielz that this can only be an option, if at all.

**Comment by D759** [comment] 2016-02-05 20:48
I agree, it should definitely be an option (as it is in foobar)

The reason i want this feature is simply when I switch to QL (e.g. look at the song's name), the blue background is immediately visible, esp. compared to the play symbol, so I am a little confused everytime.

So it is just a minor incovenience.

**Comment by declension** [comment] 2016-02-05 21:12
Sounds reasonable.... actually as a user this actually makes _more_ sense to me than the current [Follow Cursor plugin](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/playorder/follow.py) which does pretty much the opposite, but not for everyone.

Also calling it _select current song_ might be more intuitive.

**Comment by lazka** [comment] 2016-02-06 10:29
So is it more a visual annoyance or do you want to move the selection with the current song?

Asking as an alternative could also be to remove the selection on song change if the selection was caused by "activating" a song by double click etc.

**Comment by D759** [comment] 2016-02-06 12:20
Yes, it is a visual thing. The blue highlighting is simply the most clearly visible indicator.

To remove the selection on song change would at least prevent the "falsle" indication for me...  But I still would find the (optional) highlighting of the playing song in the playlist visually the most appealing to me

**Comment by lazka** [comment] 2016-02-06 14:45
What about this?

![screenshot from 2016-02-06 15-40-16](https://cloud.githubusercontent.com/assets/991986/12867243/862ec688-cce8-11e5-93c1-68ff283bbe3c.png)

**Comment by D759** [comment] 2016-02-07 08:01
Looks interesting... the light grey should catch less immediate attention than the blue highlighting

**Comment by lazka** [comment] 2016-02-07 10:34
It's an additional highlight of the current song. The selection color is still the same.

I've pushed it to master for now. Feedback welcome.. we can also remove it again.

**Comment by spxxxk** [comment] 2016-02-07 19:24
I like the idea but it could look better on my dark theme. Current track is now white on light grey which is (a little bit) harder to read than the usual white on dark. Looks good on Ubuntu's Ambiance theme though.
Possibility to choose background color ? Maybe as an entry in the config file.

**Comment by lazka** [comment] 2016-02-07 19:27
Which theme?

**Comment by spxxxk** [comment] 2016-02-07 19:40
Good question ! Made me remember I use an heavily hacked (by myself) Ambiance theme. So if it looks good on proper dark themes, ignore my comment .. That's my problem ! 

Attached screenshot of my theme.
![ss](https://cloud.githubusercontent.com/assets/11503399/12874752/dae433a0-cdda-11e5-9423-7da6b8ea0b91.jpg)

**Comment by lazka** [comment] 2016-02-07 19:55
ok, thanks, this is using ".entry:backdrop:insensitive {}" for the background color.

**Comment by urielz** [comment] 2016-02-08 01:35
Nice! Definitely looks better than the current look.

**Comment by D759** [comment] 2016-02-08 18:31
I agree, it does look good!
The currently playing song is easily identifiable at first glance

**Comment by lazka** [comment] 2016-02-18 14:00
Removing the selection on activate is tricky as it needs some event hackery because GTK+ handles it internally, and I'm not sure if that's safe.

So I'm closing this for now. If needed we can add a plugin which makes the selection follow the playing song, shouldn't be too hard. Please post here or open a new issue if such a plugin is still wanted.

**Closed by lazka** 2016-02-18 14:00 UTC
Labels: discussion
