### ISSUE TITLE
Versioned tag mapping

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1215] opened 2015-03-15 00:25 UTC
Original [issue 1215](https://code.google.com/p/quodlibet/issues/detail?id=1215) created by reiter.christoph on 2013-07-10T13:57:45.000Z:

Related: Issue #1179, Issue #48

Problem:
- Changing the tag mapping changes the tags after a reload or results in mixed mappings with new files.
- Opening the TXXX namespace will delete all TXXX frames after tag editing.

Possible solution:
- Add a ~version field which contains an integer of the tag mapping version which was used to load the file.
- Somehow use it to fix the above :)

**Comment by CreamyCookie** [comment] 2019-07-26 11:44
Closing this as duplicate of #1590.

**Closed by CreamyCookie** 2019-07-26 11:44 UTC
Labels: enhancement
