### ISSUE TITLE
Right-To-Left Text Messes Up Display

### ISSUE THREAD

**Issue by ShadiZade** [quodlibet/quodlibet#4023] opened 2022-06-22 17:36 UTC
System Info: Manjaro KDE 21.3.0 Ruah, Font: Ubuntu Arabic, Quod Libet 4.5.0

The \<length\> in the display is reversed (e.g. showing 00:3 instead of 3:00) when the name of the song is in Arabic, which is a right-to-left language. When the song name is in English or any other left-to-right language, the \<length\> is correct.

Actual example: `بيروت ست الدنيا (9∶51)`
What it should look like: `بيروت ست الدنيا (9:51)`

This is the display HTML:
`[span weight='bold' size='large']<title>[/span]<~length| (<~length>)><version|
[small][b]<version>[/b][/small]><~people|
by <~people>><album|
[b]<album>[/b]<discnumber| - Disc <discnumber>><discsubtitle| - [b]<discsubtitle>[/b]><tracknumber| - Track <tracknumber>>>`

**Comment by declension** [comment] 2022-06-26 19:07
Hmm maybe we need to add a `&lrm;` before any numeric tags? I'm not at all sure here

**Comment by ShadiZade** [comment] 2022-06-27 07:04
> Hmm maybe we need to add a `&lrm;` before any numeric tags? I'm not at all sure here

I don't know, are you sure this won't just mirror the problem, whereupon the \<length\> of English songs will get reversed? I'm no programmer at all, but maybe there's a way to exempt the length from right-to-left formatting.

**Comment by declension** [comment] 2022-06-27 07:32
> > Hmm maybe we need to add a `&lrm;` before any numeric tags? I'm not at all sure here
> 
> I don't know, are you sure this won't just mirror the problem, whereupon the <length> of English songs will get reversed? I'm no programmer at all, but maybe there's a way to exempt the length from right-to-left formatting.

Hopefully not - it's a [left-to-right marker](https://en.wikipedia.org/wiki/Left-to-right_mark) so will force that direction and it sounds like all languages [we support] will want the numeric tags in left-to-right direction (I think)

**Comment by ShadiZade** [comment] 2022-06-27 14:48
Okay, where exactly should I put this tag?

**Comment by ShadiZade** [comment] 2022-09-19 06:14
Any progress on this? It's still an issue.

**Comment by declension** [comment] 2022-09-19 09:11
@ShadiZade sorry no. I had a look but it's more complicated than I thought

**Comment by declension** [comment] 2022-09-20 19:59
@ShadiZade Can you try something like this for your display pattern

```
[span weight='bold' size='large']<title>[/span]\U0000200E<~length| (<~length>)><version| [small][b]<version>[/b][/small]><~people| by <~people>U0000200E><album| [b]<album>U0000200E[/b]<discnumber| - Disc <discnumber>><discsubtitle| - [b]<discsubtitle>[/b]><tracknumber| - Track <tracknumber>>>
```

**Comment by dseomn** [comment] 2024-02-10 22:08
Isn't this a duplicate of #3190?

**Comment by declension** [comment] 2024-02-11 08:06
Thanks, yes near enough so closing this one

**Closed by declension** 2024-02-11 08:06 UTC
Labels: bug, UI, help-wanted
