### ISSUE TITLE
Search causes quodlibet to crash/panic when paned browser preferences include # symbol

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1196] opened 2015-03-15 00:22 UTC
Original [issue 1196](https://code.google.com/p/quodlibet/issues/detail?id=1196) created by am4c130d on 2013-06-25T13:04:42.000Z:

I use a custom paned browser - specifically one pane is

&lt;album&gt;: &lt;discsubtitle|&lt;discsubtitle&gt;: |&lt;~#disc&gt;:&gt;&lt;~#track&gt; &lt;title&gt;:(&lt;~length&gt;)

~#disc is used to change discnumber formatted 1/1 to display 1
~#track is used to change tracknumber formatted 1/1 to display 1

The above panel config causes the attached dump report.  If it is modified to the below line 

&lt;album&gt;: &lt;discsubtitle|&lt;discsubtitle&gt;: |&lt;discnumber&gt;:&gt;&lt;tracknumber&gt; &lt;title&gt;:(&lt;~length&gt;)

the search works correctly.

Quodlibet 2.4
GTK+: 2.24.18 / PyGTK: 2.24.0
GStreamer: 0.10.36.0 / PyGSt: 0.10.22
Python 2.7.5+
Debian Jessie

For completeness, the other two panes I use are

genre

&lt;albumartistsort|&lt;albumartistsort&gt; &lt;small&gt;&lt;i&gt;&lt;originaldate| &lt;originaldate&gt;|&lt;date&gt;&gt;&lt;\/i&gt;&lt;\/small&gt; &lt;album&gt;|&lt;albumartist|&lt;albumartist&gt; &lt;small&gt;&lt;i&gt;&lt;originaldate|   &lt;originaldate&gt;|&lt;date&gt;&gt;&lt;\/i&gt;&lt;\/small&gt; &lt;album&gt;|&lt;author|&lt;album&gt; &lt;small&gt;&lt;i&gt;by&lt;\/i&gt;&lt;\/small&gt; &lt;author&gt;|&lt;composer|&lt;album&gt;&lt;conductor|  &lt;small&gt;&lt;i&gt;conducted by&lt;\/i&gt;&lt;\/small&gt; &lt;conductor&gt;&gt;|&lt;artistsort|&lt;artistsort&gt; &lt;small&gt;&lt;i&gt;&lt;originaldate|&lt;originaldate&gt;|&lt;date&gt;&gt;&lt;\/i&gt;&lt;\/small&gt; &lt;album&gt;|&lt;artist|&lt;artist&gt; &lt;small&gt;&lt;i&gt;&lt;originaldate|&lt;originaldate&gt;|&lt;date&gt;&gt;&lt;\/i&gt;&lt;\/small&gt; &lt;album&gt;&gt;&gt;&gt;&gt;&gt;&gt;

with the problematic pane last.

Thanks

**Comment by declension** [comment] 2021-11-07 14:00
Can't reproduce and is >8 years old, closing

**Closed by declension** 2021-11-07 14:00 UTC
Labels: bug
