### ISSUE TITLE
Crash when scanning library on windows 7

### ISSUE THREAD

**Issue by keiter** [quodlibet/quodlibet#1696] opened 2015-10-05 19:13 UTC
Hi,
I've encountered a bug while using quod libet on windows 7. If I "Refresh Library" right after having rebooted the computer, quod libet crashes. (If you have "refresh library on start" toggled on this means it crashes as soon as you start it.) The bug stops occuring if I do anything that causes sound to play from another program, i.e. like watching a youtube video. It will then keep working normally until I power off the computer, and then on next boot I will have the same problem.

Please let me know if there's any way I can help you narrow down the bug causes. I'd normally provide more info in a bug report but I usually don't debug on Windows. :)

**Comment by lazka** [comment] 2015-10-05 19:20
Does it depend on the active browser maybe?

**Comment by urielz** [comment] 2015-10-06 20:09
I didn't come across this issue on Windows 8.1. But I'll double-check and report back.

**Comment by keiter** [comment] 2015-10-08 18:53
@lazka It seems to depend on another program playing sound first before it'll work. I can also avoid it crashing by say opening a movie in VLC. It also appears I was wrong when I said it's fixed until reboot; It's more that it's fixed as long as the "other program" is still running. Again sticking with the Firefox example I can open Firefox, play a youtube video, and the open QL and Scan Library with no problems. But If I then quit Firefox and rescan it won't work.

I should aslo say that I produced this on 3.4.1. Will try 3.5 and see if it's still there.

**Comment by keiter** [comment] 2015-10-08 19:36
I can also reproduce it on 3.5.

**Comment by lazka** [comment] 2015-10-09 16:43
weird.. no idea atm.

**Comment by keiter** [comment] 2015-10-11 11:00
Do you have any suggestion of log files I can look at or any other method of seeing what my QL is doing when it crashes? Then I can at least figure out if it's really a bug or just some sort of OS or sound issue.

**Comment by lazka** [comment] 2015-10-11 11:09
There is a quodlibet-cmd.exe in the same folder that quodlibet.exe is in, which can be started in the terminal e.g. "quodlibet-cmd.exe --debug" and that will show some logging output. There is also "--no-plugins" for ruling out plugins.

**Comment by keiter** [comment] 2015-10-11 11:20
Ok, did that, got following output:
```
C:\Users\keiter>"C:\Program Files (x86)\Quod Libet\bin\quodlibet-cmd.exe"
**
Gtk:ERROR:gtkprogressbar.c:604:tick_cb: assertion failed: (priv->pulse2 > priv->
pulse1)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by lazka** [comment] 2015-10-11 11:36
Thanks. Looks like a gtk+ bug. I'll include a newer version with 3.5.1 - maybe that helps.

**Comment by keiter** [comment] 2015-10-12 09:37
Ok, I'll give it a try when that comes out.

**Comment by keiter** [comment] 2015-10-17 13:02
Hmm, so I tried reproducing the bug on 3.5.1, and I still get it. Weirdly enough, I also determined that it doesn't crash if I use the --debug flag...

**Comment by lazka** [comment] 2015-10-18 08:20
> Hmm, so I tried reproducing the bug on 3.5.1, and I still get it. Weirdly enough, I also determined that it doesn't crash if I use the --debug flag...

I'll post here once I have something to test. I didn't want to change the gtk+ version for 3.5.1 as I didn't have much time to test for regressions.

Regarding the --debug flag: I looks like it's a timing problem so --debug slowing things down could change the result.

**Comment by EllaMcC** [comment] 2015-11-20 18:20
Just a note that I'm having this same issue, also on Win7, and it only started after a bunch of Windows updates on 13th November. I can list the updates I allowed, but I don't know enough to figure out which might cause a runtime error. Most were security updates, but here's a list:

*Update for Windows 7 for x64-based Systems (KB3107998)
Installation date: ‎11/‎13/‎2015 10:23 AM
Install this update to resolve issues in Windows. For a complete listing of the issues that are included in this update, see the associated Microsoft Knowledge Base article for more information. After you install this item, you may have to restart your computer.
More information: 
http://support.microsoft.com/kb/3107998

*And these two:
  * Security Update for Microsoft .NET Framework 4.5, 4.5.1 and 4.5.2 on Windows 7, Vista, Server 2008, Server 2008 R2 x64 (KB3098781)
Installation date: ‎11/‎13/‎2015 10:23 AM  http://support.microsoft.com/kb/3098781
  * Security Update for Microsoft .NET Framework 4.5, 4.5.1 and 4.5.2 on Windows 7, Vista, Server 2008, Server 2008 R2 x64 (KB3097996)
Installation date: ‎11/‎13/‎2015 10:28 AM  http://support.microsoft.com/kb/3097996

* And all of the following:
  * http://support.microsoft.com/kb/3097989 -- Security Update for Microsoft .NET Framework 3.5.1 on Windows 7 and Windows Server 2008 R2 SP1 for x64-based Systems (KB3097989)
  * 7 different "Security Update for Windows 7 for x64-based Systems"
    * (KB3100213) - (I'm sure you know this, but they work like so:) http://support.microsoft.com/kb/3100213
    * (KB3101722)
    * (KB3097877)
    * (KB3092601)
    * (KB3101746)
    * (KB3101246)
    * (KB3081320)

* Then a Defender update:
  * Definition Update for Windows Defender - KB915597 (Definition 1.209.2685.0)
Installation date: ‎11/‎13/‎2015 10:19 AM 
http://www.microsoft.com/athome/security/spyware/software/about/overview.mspx
Help and Support: 
http://go.microsoft.com/fwlink/?LinkId=52661

* Finally the: Windows Malicious Software Removal Tool x64 - November 2015 (KB890830)
After the download, this tool runs one time to check your computer for infection by specific, prevalent malicious software (including Blaster, Sasser, and Mydoom) and helps remove any infection that is found. If an infection is found, the tool will display a status report the next time that you start your computer. A new version of the tool will be offered every month. If you want to manually run the tool on your computer, you can download a copy from the Microsoft Download Center, or you can run an online version from microsoft.com. This tool is not a replacement for an antivirus product. To help protect your computer, you should use an antivirus product.
http://support.microsoft.com/kb/890830

* and lastly:
  * Cumulative Security Update for Internet Explorer 11 for Windows 7 for x64-based Systems (KB3100773)
Installation date: ‎11/‎13/‎2015 10:25 AM
http://support.microsoft.com/kb/3100773

**Comment by lazka** [comment] 2016-02-17 14:36
I currently can't update gtk+ as the new builds don't work wine and we use that in our build process. I guess this has to wait for #1718

**Comment by lazka** [comment] 2016-03-03 18:14
Could you try the newest build?

https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.6.-1-rev7983-3f0fb55-installer.exe
https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.6.-1-rev7983-3f0fb55-portable.exe

**Comment by keiter** [comment] 2016-03-06 13:01
@lazka I installed that build, and it looks like that fixed the issue for me.

**Comment by lazka** [comment] 2016-03-06 18:18
Thanks for testing

**Comment by EllaMcC** [comment] 2016-03-07 19:18
Sorry it took me so long to finally get round to testing this on my Win7 machine -- this build works like a charm. Not only does it no longer crash, but it handles my huge library with what seems like delicate sensibilities. Thanks so much for all the work.

**Comment by keiter** [comment] 2016-03-15 13:56
Unfortunately, this looks like it regressed since fixing #1880 for me.

**Comment by Telemin** [comment] 2016-09-01 22:54
I can confirm that this bug still exists for QL 3.7.0:

Gtk:ERROR:gtkprogressbar.c:611:tick_cb: assertion failed: (priv->pulse2 > priv->pulse1)

**Comment by lazka** [comment] 2016-11-06 20:13
If anyone is feeling adventurous, there is now a new installer based on msys2: https://github.com/quodlibet/quodlibet/issues/1718#issuecomment-258706608

**Comment by lazka** [comment] 2016-11-11 13:59
Let's hope this is fixed now. Please scream if the issue persists with the new installer.

**Closed by lazka** 2016-11-11 13:59 UTC
Labels: bug, windows
