### ISSUE TITLE
Support for retina devices?

### ISSUE THREAD

**Issue by Alhadis** [quodlibet/quodlibet#1564] opened 2015-03-22 23:15 UTC
Just installed Quodlibet on 3.3.1 on Mac OS 10.9.5... the interface appears very grainy and low-res. Has the application been optimised for retina/high-density screens? I'm running a MacBook Retina Pro.

**Comment by declension** [comment] 2015-03-23 16:00
I don't think it's been tested on an actual Mac (with actual Retina display), so sounds likely enough. I can try to replicate this week from the latest build though.

Either way, could you attach a screenshot please?

**Comment by lazka** [comment] 2015-03-23 16:18
I tried enabling it once on a retina mac book (setting NSHighResolutionCapable in Info.plist) and it messed up image sizes, both drawn by GTK+ and QL, so I assume this needs work in GTK+ and/or cairo, or I did something wrong back then.

**Comment by Alhadis** [comment] 2015-03-27 13:23
Sorry for the slow reply, was a hellish week.
![screen shot 2015-03-28 at 12 19 39 am](https://cloud.githubusercontent.com/assets/2346707/6868496/3eb16776-d4e0-11e4-9031-a00deb1e4b4a.png)

I've attached a screengrab of Quodlibet on my system, with other programs running behind it for easier comparison. You can see things are a little... grainy.

![screen shot 2015-03-28 at 12 16 48 am](https://cloud.githubusercontent.com/assets/2346707/6868544/8f948af6-d4e0-11e4-976f-43f7fe6d0a39.png)

**Comment by kaffeeundsalz** [comment] 2015-07-02 08:02
I've been playing around with this issue a bit and noticed that when you add a `<key>AppleMagnifiedMode<key> <false />` to *org.quodlibet.plist*, Quod Libet already looks quite nice on retina displays. At least I figured this is what [Retinizer](http://retinizer.mikelpr.com) does to, well, retinize applications that aren't yet HiDPI compatible out of the box. Note that the interface of Quod Libet looks smooth except for some specific UI elements like checkboxes and some buttons:

![quodlibet_settings](https://cloud.githubusercontent.com/assets/4942960/8472073/707adbd4-209e-11e5-8b74-56391487472c.png)

There is however a bug that makes retina experience in Quod Libet quite odd. Whenever there are scrollbars involved, text rendering immediately changes back to blurry non-retina. An easy way to reproduce this is using the album list view. First have a look at the Quod Libet main window with no scrollbars:

![quodlibet_retina](https://cloud.githubusercontent.com/assets/4942960/8472177/5bebf102-209f-11e5-8b80-7fa0a33259c2.png)

Here, I have selected a single album in the left pane to limit the number of titles so they all fit into the window. Now this is what happens when selecting "all albums":

![quodlibet_halfblurry](https://cloud.githubusercontent.com/assets/4942960/8472258/e95ab6cc-209f-11e5-8436-2e1a5e923bb4.png)

As the vertical scrollbar appears at the very right of the window, the tracklist gets blurry. Note that the left album view pane is still retina. We can change this by slightly moving the split pane divider to the left:

![quodlibet_blurry](https://cloud.githubusercontent.com/assets/4942960/8472311/706ab996-20a0-11e5-935e-c2cc4bbeaf1d.png)

Now that the left pane has a horizontal scrollbar, it gets blurry too. This happens with all windows and panes as soon as scrollbars are involved. Do you have any idea what's going on there? Does it help you in any way with working on HiDPI support?

**Comment by lazka** [comment] 2015-07-02 14:52
No idea (no retina Mac..), but if setting AppleMagnifiedMode has no negative site effects we could enable it be default at least.

**Comment by lazka** [comment] 2015-07-02 15:03
#gtk+ suggested to try setting ```GTK_DEBUG=no-pixel-cache``` (as an env var)

**Comment by kaffeeundsalz** [comment] 2015-07-05 12:19
Setting `GTK_DEBUG=no-pixel-cache` perfectly solves the above issue for me, so more pixelated non-retina-fallback with this. Handling environment variables has become rather cumbersome in Yosemite, but [here's how Apple wants you to do it](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPRuntimeConfig/Articles/EnvironmentVars.html). I'm fine and fastest with just starting Quod Libet via command line and let it inherit the Terminal session. For me, it runs fine in Retina mode now, except we'd still need some high resolution UI elements like checkboxes and menu icons for perfect support. As to enabling AppleMagnifiedMode by default, I'm afraid I don't know how it affects the program UI on standard resolution displays.

**Comment by lazka** [comment] 2015-07-05 13:47
Thanks for testing. I'll try setting/testing AppleMagnifiedMode in my OS X VM and the env var can be set in our start bash script. Also I'm not sure what the performance implications are for disabling pixel cache.. but mac books are usually on the higher end regarding performance, so this should be fine I guess.

**Comment by lazka** [comment] 2015-07-11 15:17
Here is a new (test) build: https://bitbucket.org/lazka/quodlibet/downloads/QuodLibet-3.4.1.zip

Some icons still seem to be blurry, not sure why yet.

**Comment by lazka** [comment] 2015-07-17 08:40
Upstream bugs:

https://bugzilla.gnome.org/show_bug.cgi?id=710501
https://bugs.freedesktop.org/show_bug.cgi?id=69796

**Comment by kaffeeundsalz** [comment] 2015-07-31 13:29
As far as I can see, QuodLibet delivers out of the box retina experience with the above build, so thank you for this!

> Some icons still seem to be blurry, not sure why yet.

That's probably because they're simply too small to look good on HiDPI screens. We've seen similar issues on other GTK based applications like e.g. GIMP. The provided icon sizes need to match the UI scaling factor, so we probably need better GTK support for high resolution screens to fix the blurry icons.

**Comment by lazka** [comment] 2015-07-31 18:06
The next build will include some more retina fixes; fixing the blurry icons and blurry images when dragging things around. Once that's out I will close this.

**Comment by lazka** [comment] 2015-08-22 11:15
New builds with (hopefully) full retina support: https://quodlibet.readthedocs.org/en/latest/downloads.html#macosx

also all plugins should now work except webkit based ones.. I'll look into adding those for 3.5

**Closed by lazka** 2015-08-22 11:15 UTC
Labels: bug, forwarded-upstream, osx
