### ISSUE TITLE
Changes to metadata are lost when a song ends

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#3534] opened 2021-01-08 16:23 UTC
Steps to reproduce
------------------
Play a song.

Edit its metadata with Alt-Enter.

I change some tags.
When the song finishes, all my changes become lost.

Expected Output
---------------
When another song is playing, nothing special happens to the edited tags

Actual Output
-------------
Already explained

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
KDE Neon based on Ubuntu 20.04

### If it's audio-related, what back-end?
Unrelated

Additional Information
----------------------
If I rate the edited song in the grid or add it to a playlist, I also lose my changes.

**Comment by declension** [comment] 2021-01-11 20:49
Is this a duplicate of #3484 @DavidPerezIngeniero ?

**Comment by declension** [comment] 2021-04-10 19:26
Closing as duplicate for now - but please re-open and clarify if not.

**Closed by declension** 2021-04-10 19:26 UTC
Labels: bug

**Comment by DavidPerezIngeniero** [comment] 2021-04-13 06:06
Yes it is a duplicated
