### ISSUE TITLE
Renaming files containing Chinese characters results in an error

### ISSUE THREAD

**Issue by marmistrz** [quodlibet/quodlibet#2620] opened 2017-11-05 18:09 UTC
Example filename: 

> 唐朝 - 梦回唐朝. 01 - 梦回唐朝.flac

**Comment by lazka** [comment] 2017-11-05 18:23
Which operating system?

**Comment by marmistrz** [comment] 2017-11-05 18:24
Arch Linux, Python 3.6.3

**Comment by frestr** [comment] 2018-05-19 12:43
Could you provide some more details on this? Like how exactly you are renaming the file (steps to reproduce) and what the error is.

**Comment by CreamyCookie** [comment] 2019-06-24 16:39
Cannot reproduce. No error here.

Closing this one as incomplete.

**Closed by CreamyCookie** 2019-06-24 16:39 UTC
