### ISSUE TITLE
label:enhancement  CD reading capability again

### ISSUE THREAD

**Issue by moebius1** [quodlibet/quodlibet#2168] opened 2016-12-23 16:25 UTC
Bonjour,

I think that reading cd capability would be nice ; In quodlibet there's a file browser, so why not add a cd-rom entry ?

Well, I say that because I use quodlibet for dance learning music (nice feature that tempo change ! ); sometime, a teacher come with a CD and says : « well I'm going to teach you a dance ; would you please set up the 5th track of this CD ? »
I say yes and launch rhythmbox (no tempo change anymore :( )on my poor old laptop with its poor 1Go memory, just for readind this bloo.. cd, is that fair ? If I could do everything with just Quodlibet, it would be very nice...
I'm not really knowing what kind of work is necessary to put in this feature but I suppose there's a lot of libraries that could be put in quodlibet with not too much pain ?
If it's the case, please do, We are numerous that would be very grateful for this, I'm sure ! If it's just an ideological choice, It seems that «quodlibet» means « as you want» isn't true ? :)

Just another thing (please don't try to kill me) it would be nice if Quodlibet could read audio track of any video...but it's another story !

cordialement,

**Comment by declension** [comment] 2016-12-27 21:24
Sounds like #163 ...

**Comment by declension** [comment] 2016-12-31 11:22
Closing as duplicate of #163

**Closed by declension** 2016-12-31 11:22 UTC
