### ISSUE TITLE
Different add Tag interface for mp3 vs m4a

### ISSUE THREAD

**Issue by slackmage** [quodlibet/quodlibet#3330] opened 2020-03-24 17:54 UTC
On m4a files you can't type in a custom tag. You can only select from a list.

![quodlibet_Ow1EiRBdxm](https://user-images.githubusercontent.com/230274/77459907-c4c69900-6dd6-11ea-8913-d6598d88f158.png)
![quodlibet_MX9DcN5bBQ](https://user-images.githubusercontent.com/230274/77459908-c55f2f80-6dd6-11ea-9706-c2189b6b98bc.png)

**Comment by DavidPerezIngeniero** [comment] 2020-05-23 09:47
Is there a technical reason to do so?
Or is it a bug?

**Comment by declension** [comment] 2020-05-25 08:38
Yes this is by design - QL takes the approach that m4a tags are not freeform as per other formats (id3, vorbis). AIUI the existing tags are reverse were (originally) reverse engineered from "what iTunes supports" which was always the driver of that format.

Perhaps now in 2020 this is no longer so true and freeform m4a is more relevant - I don't know. The ticket for _that_ is #323 so perhaps we should close this in favour of that.

**Comment by CreamyCookie** [comment] 2020-09-04 17:25
Closing this as a duplicate of #323

**Closed by CreamyCookie** 2020-09-04 17:25 UTC
Labels: discussion
