### ISSUE TITLE
duplicate albums in "album list" view

### ISSUE THREAD

**Issue by ilmetallo** [quodlibet/quodlibet#1620] opened 2015-05-27 07:07 UTC
Hi!

It often happens, that tracks from the same album are divided in two duplicate albums, in the "album list" view.

For example, I've just opened quodlibet and I have two "Sweatshops" albums for the same artist. The tags seems identical (same album title, same artist, same date, same genre).
The album has 9 tracks. 2 of them (in this case) are assigned to one duplicate, and the other 7 are assigned to the other duplicate.
If I use the "refresh song" plugin, the songs are merged correctly in a single album.

Interestingly, this behaviour is shown also in the "album collection" view but not in the "paned browser" (which lists the tracks correctly grouped in albums)

**Comment by declension** [comment] 2015-05-27 09:10
Thanks for the report. When did this start happening (and what version of QL are you using exactly)?

As a long-term / worthwhile workaround, you can use `musicbrainz`-* or `labelid` to tag your albums uniquely. See [the FAQ entry](http://quodlibet.readthedocs.org/en/latest/guide/faq.html#player) about distinguishing albums

(As usual, I've now noticed that the FAQ page needs a lot of updating).

**Comment by ilmetallo** [comment] 2015-06-24 07:46
Hi! Sorry for the very huge delay.

I've tried 3 different versions: 3.2.2-1 (vivid repository), 3.4.1-0 (from stable ppa) and 3.4.99 (from unstable ppa). This duplicate album behaviour appears in all of them

So, probably I'm doing something wrong. I have all my library updated with musicbrainz tags (I've been using Picard for years)

I've just noticed a couple of things
1. (I display the columns with replaygain album and track info) in one case, the "duplicate" albums contain songs with replaygain values formatted differently (2 decimals in one album, more decimals in the other). I don't know the reason of these different formats.
2. In another case, the replaygain were formatted in the same way, howevere I found a problem in the albumartistsort tag, where the artist name were repeated several time. but differently between the two duplicate albums. e.g. in one of the two duplicate, the songs' albumartistsort tag contain 4 repetition of the artist name, in the other duplicate, the songs' tag contain 8 repetition of the artist name

**Comment by lazka** [comment] 2015-06-24 17:49
We currently use the sort tags as album keys (for speed, but that should be evaluated/fixed). So make sure the albumartistsort is the same across all files.

**Comment by ilmetallo** [comment] 2015-06-25 12:15
Today I opened quodlibet, and I found an album splitted in two duplicates. So I checked the sort tags and they were same for all the mp3s.
The only difference I could see was again the different format of the replaygain values.
Let me explain better:
In the Album List view, I have two custom headers: replaygain_album_gain and replaygain_track_gain
When an album is split in two duplicates (containing different tracks), in one duplicate (which in this case contains tracks 1,2,11,12,13) the replaygain values are displayed with 6 decimals, in the other duplicate (containing all the other tracks of the album) the replaygain values are displayed with 2 decimals.
When I use the "refresh song" plugin on these tracks, the displayed values for replaygain are all formatted to 6 decimals, and the two duplicate album are merged correctly as a single album.

**Comment by declension** [comment] 2015-06-30 10:12
I'd venture that what you've seen are two manifestations of the same underlying issue: that your tags saved in the library were produced by two different libraries / apps, and one was being interpreted quite differently by QL from the other, but fixed on a refresh. Perhaps these have been modified externally, perhaps it's a QL bug, perhaps it's in the grey area of "non-compliant" tags producing slightly arbitrary results.

I'm pretty sure that the formatting of RG values _itself_ is not the issue with albums being split, but that some more album-like tags (see the FAQ) are being affected here too which then causes the inclusion in albums to be changed.

Let us know if you want to keep this issue open, or if you're happy to sort the tags out, rebuild your QL library, and see what happens.

### Some asides
* QL (or rather, the ReplayGain plugin) currently uses **2** decimal places when _saving_ those RG values. 
* The _numeric_ columns `#replaygain_album_gain` and `#replaygain_track_gain` are available in all recent versions of QL, and this looks a lot nicer in a crowded songlist window (2dp always, and supports proper sorting etc). Perhaps these would be useful to you too.

**Comment by lazka** [comment] 2016-03-04 14:56
There was a related bug fixed by a1bfab5e99c554ead3 which resulted in the album list view getting out of sync. Not sure if the problem described here could be caused by it.

**Comment by declension** [comment] 2017-06-30 06:54
Can we close this now?

**Closed** 2019-07-26 14:19 UTC
Labels: needinfo
