### ISSUE TITLE
micro pause/glitch between two tracks which were designed to run into each other

### ISSUE THREAD

**Issue by alan12345678** [quodlibet/quodlibet#2964] opened 2018-09-12 13:20 UTC
Not sure if this is directly a QL issue but it's become extremely annoying.

Usually QL behaves flawlessly, just switching from current track to next seamlessly. But in the case of (currently) one particular album I'm having an issue with an audible glitch which appears in the form of a very slight break in the audio. The album in question is Pink Floyd's "The Wall".

To reproduce this issue: Disc 1: tracks 2 & 3 are designed to run directly into each other with no pause. Same applies with Disc 1: tracks 4 & 5.

If I play track 2 alone it plays to the end and stops (abruptly, because it's cut to run directly into track 3).
If I play track 3 alone, it starts at the end point of track 2 and plays perfectly.

If however I have the entire album in the play window (I use the file browser window at left), as track 2 finishes and track 3 is loaded, there's a very slight pause in the form of a "bump" (is what it sounds like) just as soon as track 3 begins. The same issue happens with tracks 4 & 5 i.e. individually they play fine, but played back to back there's the same pause at the beginning of track 5.

I've re-ripped the CD, have played both the original and remastered versions. I have examined the tracks in Audacity - no visible glitches or errors. I have set the seek time to both maximum and minimum values and restarted each time. No difference the error persists.

This effect is NOT noticed on other albums like DJ mixes where tracks run into each other.

I'm mystified as to why this is happening on this particular set of tracks.

**Comment by lazka** [comment] 2018-09-14 19:10
In case it's MP3 that's because GStreamer doesn't support gapless playback there.

**Comment by alan12345678** [comment] 2018-09-14 19:12
Oh okay - THANKS for clarifying :)

Does this mean if I rip it to, say, FLAC the problem might disappear?

Supplementary question: does this also mean that as general system updates appear, this 'glitch' might end up being sorted?

**Comment by lazka** [comment] 2018-09-14 19:15
> Does this mean if I rip it to, say, FLAC the problem might disappear?

If it's that particular problem, then yes. Using opus would also work.

> Supplementary question: does this also mean that as general system updates appear, this 'glitch' might end up being sorted?

Unlikely, this problem is known for years and no one bothered so far to implement it.

**Comment by CreamyCookie** [comment] 2019-07-24 08:37
Closing this as a duplicate of #2347.

**Closed by CreamyCookie** 2019-07-24 08:37 UTC
