### ISSUE TITLE
Quodlibet 3.5.1 another UI freeze

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#1775] opened 2016-01-02 19:57 UTC
I've already reported a UI freeze in a comment to issue #1736 . This is another one.

Using the Album List browser, I select a song and attempt to 'Move to Trash'. If I don't have appropriate permissions an error dialog window displays, and after I close it, the 'Moving x/y - Cancel/Stop' dialog window remains and the browser UI is frozen. 

The player continues playing and the main window View browser UI is still functional but the Album List window UI has frozen. The only way I've found to resolve the freeze is to kill Quodlibet.

Ubuntu Linux version Ubuntu 14.04.03 LTS
Quodlibet 3.5.1

The steps to reproduce:
Music | Open browser | Album List window open
Select track, context menu - Move to Trash
permissions error dialog
Moving 0/17 dialog window - no response from Cancel or Stop

**Comment by lazka** [comment] 2016-01-03 04:16
Thanks.

Regarding your "What's the etiquette for bumping a Git issue?" mail. Both posting reminders to existing issues or opening new ones is fine.

**Comment by davidSchlosser** [comment] 2016-01-05 22:19
This is probably same as #1339 In the meantime, I've changed the trash folder permissions as Andrew Chadwick suggested in a comment there.

**Comment by declension** [comment] 2016-01-06 21:36
Thanks, closing as duplicate of #1339 (re-open if it turns out to be different)

**Closed by declension** 2016-01-06 21:36 UTC
