### ISSUE TITLE
Encrypt scrobbler password

### ISSUE THREAD

**Issue by bassstorm** [quodlibet/quodlibet#2962] opened 2018-09-07 21:04 UTC
Scrobbler password stored as clear text in quodlibet/config file:

> scrobbler_password = _\<actual password goes here\>_

The file is likely open for reading by any user on any major Linux distro. Is it possible to apply some security over such sensitive pieces of information? Thanks!

**Comment by lazka** [comment] 2018-09-07 21:07
Yeah, this came up in #1242.

**Comment by MBybee** [comment] 2019-11-20 20:59
Still an issue (win10 2019).

**Comment by CreamyCookie** [comment] 2021-04-19 12:57
Closing as this is basically a duplicate of #2784: Use auth API for Last.fm Scrobbler plugin (instead of plain text user / password)

**Closed by CreamyCookie** 2021-04-19 12:57 UTC
Labels: enhancement
