### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by Hunter16g** [quodlibet/quodlibet#1758] opened 2015-12-08 16:57 UTC
Hi,
Recently Quodlibet regularly shows an error message saying I should open an issue, so here I am. 
I'm afraid I don't understand theses dumps, I hope it will help.
[Dump_20151129_213249.txt](https://github.com/quodlibet/quodlibet/files/55721/Dump_20151129_213249.txt)
[Dump_20151130_163723.txt](https://github.com/quodlibet/quodlibet/files/55723/Dump_20151130_163723.txt)
[Dump_20151130_163724.txt](https://github.com/quodlibet/quodlibet/files/55722/Dump_20151130_163724.txt)
[Dump_20151130_220821.txt](https://github.com/quodlibet/quodlibet/files/55724/Dump_20151130_220821.txt)
[Dump_20151202_005504.txt](https://github.com/quodlibet/quodlibet/files/55730/Dump_20151202_005504.txt)
[Dump_20151202_005512.txt](https://github.com/quodlibet/quodlibet/files/55725/Dump_20151202_005512.txt)
[Dump_20151202_005513.txt](https://github.com/quodlibet/quodlibet/files/55728/Dump_20151202_005513.txt)
[Dump_20151202_005514.txt](https://github.com/quodlibet/quodlibet/files/55732/Dump_20151202_005514.txt)
[Dump_20151202_005515.txt](https://github.com/quodlibet/quodlibet/files/55733/Dump_20151202_005515.txt)
[Dump_20151208_175228.txt](https://github.com/quodlibet/quodlibet/files/55731/Dump_20151208_175228.txt)
[Dump_20151208_175250.txt](https://github.com/quodlibet/quodlibet/files/55726/Dump_20151208_175250.txt)
[Dump_20151208_175257.txt](https://github.com/quodlibet/quodlibet/files/55729/Dump_20151208_175257.txt)
[Dump_20151208_175258.txt](https://github.com/quodlibet/quodlibet/files/55727/Dump_20151208_175258.txt)

**Comment by lazka** [comment] 2015-12-08 20:41
Thanks. Do you have the "Auto Library Update" plugin enabled? If yes can you disable it and see if things improve?

**Comment by Hunter16g** [comment] 2015-12-09 16:08
Yes, I had it enabled. I disabled it, I'll let you know if have have problems again.

**Comment by lazka** [comment] 2015-12-09 16:09
Thanks

**Comment by declension** [comment] 2015-12-18 09:27
Hmmm we should probably remove that plugin; I'm not even sure if it works at all any more.

(see  #1315)

**Comment by Hunter16g** [comment] 2015-12-18 13:13
I've got three more dumps in the past few days, not sure it is related 
[Dump_20151217_014220.txt](https://github.com/quodlibet/quodlibet/files/66594/Dump_20151217_014220.txt)
[Dump_20151217_014223.txt](https://github.com/quodlibet/quodlibet/files/66595/Dump_20151217_014223.txt)
[Dump_20151217_085837.txt](https://github.com/quodlibet/quodlibet/files/66596/Dump_20151217_085837.txt)

And I don't think the plugin worked because I refreshed the library even with it enabled.

**Comment by lazka** [comment] 2015-12-18 13:15
Thanks for the update. I guess the plugin is no the cause then.. no idea atm

**Comment by CreamyCookie** [comment] 2019-06-21 22:14
Closing this for now. Comment here if it has come up again.

**Closed by CreamyCookie** 2019-06-21 22:14 UTC
