### ISSUE TITLE
ExFalso Preferences crash

### ISSUE THREAD

**Issue by timkgh** [quodlibet/quodlibet#3801] opened 2021-09-11 18:08 UTC
Steps to reproduce
------------------
Open Preferences in ExFalso

Expected Output
---------------
See preferences

Actual Output
-------------
Crash

Test System
-----------

### Which version of Quod Libet?
ExFalso 4.4.0

### Which operating system 
macOS Catalina 10.15.7

### If it's audio-related, what back-end?

Additional Information
----------------------

```
TypeError: __init__() missing 1 required positional argument: 'parent'
------
Traceback (most recent call last):

  File "/Applications/ExFalso.app/Contents/Resources/lib/python3.8/site-packages/quodlibet/qltk/exfalsowindow.py", line 75, in prefs_cb
    window = PreferencesWindow(self)

  File "/Applications/ExFalso.app/Contents/Resources/lib/python3.8/site-packages/quodlibet/qltk/exfalsowindow.py", line 277, in __init__
    super().__init__()

TypeError: __init__() missing 1 required positional argument: 'parent'
```

**Comment by declension** [comment] 2021-09-12 08:47
Thanks. Closing as duplicate of #3591 / #3608

**Closed by declension** 2021-09-12 08:47 UTC
Labels: bug

**Comment by timkgh** [comment] 2021-09-12 20:55
Thanks. Any plans for an official release that has the fix?

**Comment by declension** [comment] 2021-09-13 07:12
@timkgh there's https://github.com/quodlibet/quodlibet/milestones/16/edit but it's pretty empty currently. This could also be a `4.4.1` I guess

**Comment by declension** [comment] 2021-09-13 07:20
Added https://github.com/quodlibet/quodlibet/issues/3808 to track

**Comment by timkgh** [comment] 2021-09-13 15:56
4.4.1 bug fix release sounds good.
