### ISSUE TITLE
ReplayGain plugin: Fatal behaviour on same-named albums.

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#1879] opened 2016-03-06 12:34 UTC
We need a solution here. QL handles my "Greatest Hits" albums from different artists as one. You can imagine the consequences.

**Comment by urielz** [comment] 2016-03-06 18:24
Besides the Album tag, other tags are used to identify different albums (with the same album title). "labelid" is one of those tags. Check the docs for further info:

https://quodlibet.readthedocs.org/en/latest/guide/browse/album.html

**Comment by declension** [comment] 2016-03-06 19:01
Annoying: yes. Obvious solution: not so much. 

I'd strongly recommend using Musicbrainz tags, the problem just goes away then (and setting `albumartist` never hurts).

See discussion in related: #1871

**Comment by CreamyCookie** [comment] 2019-06-21 22:31
Closing this as a duplicate of #1871

**Closed by CreamyCookie** 2019-06-21 22:31 UTC
