### ISSUE TITLE
Ratings not understood by other music players

### ISSUE THREAD

**Issue by deshmukhs** [quodlibet/quodlibet#2220] opened 2017-02-02 04:40 UTC
Quod Libet seems to follow ratings that are secretive and are not shared with other music applications.

I am running QL 3.8.0. And have Update Tags in Files plugin enabled. In Preferences -> Tags, Save ratings and playcounts option is selected. And in Rating scale is set for 5 *.

After I rate a song to a value, say ***, other music players can not see this value. Ratings set by other music players are not shown in QL.

**Comment by declension** [comment] 2017-02-02 08:17
See #105, #515, #849

**Comment by 3d73a4a412** [comment] 2017-05-01 23:56
I am assuming my issue is related to this one, I read #105, #515, #849 but to be honest it wasn't clear to me other than #105 was considered a higher priority (back in 2015?) and is closed now? (appologies for my noobness). 
In my case I am coming from a combination of foobar2000/jaikoz/mp3tag on primarily mp3/flac/ogg files and they seemed to work fairly well with each other on the diff formats in terms of understanding metadata that each other wrote. 
I installed lq and compared to just about all the other players out there I quite like it but there will certainly be a learning curve. First thing is ratings I guess. All my music, which I have ratings mostly 3, 4, and 5 are showing up as either 0, 2, or 5 nothing else. I am pretty much positive that a fair number of the ones marked as 5 star are not correct (I would never have marked as 5) so I am a bit stumped.

**Comment by CreamyCookie** [comment] 2019-07-24 09:19
@deshmukhs Did you also use the Update Tags in Files plugin on the songs you've rated?

**Comment by CreamyCookie** [comment] 2019-08-13 12:47
Closing this for now as `Can't reproduce`.

**Closed by CreamyCookie** 2019-08-13 12:47 UTC
Labels: needinfo
