### ISSUE TITLE
Playcounts and ratings aren't saved in tags

### ISSUE THREAD

**Issue by wifon** [quodlibet/quodlibet#3118] opened 2019-01-26 10:31 UTC
Expected Output
After setting a song rating or playing it again, rating and playcount should be saved in tags. But it isn't

(What should happen?)
Tag's should've been saved

Actual Output
rating: https://my.mixtape.moe/ohgsyi.mp4
If I rate a song, it's only applied to tags if I use "Update tags in files" plugin

playcount: https://my.mixtape.moe/npuzri.mp4
If a playcount changes, it's only applied to tags if I use "Update tag in files plugin"

Test System
-----------

Which version of Quod Libet?
4.3

Which operating system 
Mint 19.1

I have "Save rating and play counts in tags" option enabled in my quodlibet preferences.

**Comment by CreamyCookie** [comment] 2019-06-21 10:46
Seems like a duplicate of #1852. Feel free to re-open if I'm mistaken.

**Closed by CreamyCookie** 2019-06-21 10:46 UTC
Labels: bug
