### ISSUE TITLE
Multiline Tags

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#280] opened 2015-03-14 22:15 UTC
Original [issue 280](https://code.google.com/p/quodlibet/issues/detail?id=280) created by Stephan.Ritscher on 2009-08-14T20:16:24.000Z:

I have a music library with lyrics. As well for mp3s as for flacs these are
stores in a frame called &quot;lyrics&quot; (in mp3 it's a TXXX frame). I managed to
have them displayed in Quodlibet. But in the tag editor they are split -
one entry per line. Since lyrics are long, what I would expect is a preview
of the first few lines in the list view and instead of the in-place edit
box something proper for long texts.

**Comment by CreamyCookie** [comment] 2016-03-12 16:30
Has this been fixed? :)

I saw that the [viewlyrics plugin](https://github.com/quodlibet/quodlibet/blob/96f99984ab1d8fd0d02e7742f23353c4c4e25ab8/quodlibet/quodlibet/ext/events/viewlyrics.py) uses `song("~lyrics")`, or am I missing something?

**Comment by lazka** [comment] 2016-03-13 04:58
We use "newline" for separating values, so the tag edit doesn't handle it well.

We could add a hardcoded list of single value tags and handle them in a special way.

**Comment by declension** [comment] 2016-03-13 09:33
> We could add a hardcoded list of single value tags and handle them in a special way.

This seems like a good idea, and I don't think there would be too many.  `comment` is another one that I find often contains lengthy text, possibly newlines too (especially if populated from virtual tags e.g. fields from APIs...). Maybe `description` as well, though I _think_ that's usually a misunderstood tag. Probably no harm in adding it then I suppose.

**Comment by dannn-o** [comment] 2018-10-11 22:20
I had commented on the issue of embedded lyrics not displaying in issue #1628, which had another referenced thread in issue #2991, which was closed and referenced in this one.  Since a bit of time has passed, I wanted to check as to whether or not the issue I was pursuing (i.e. embedded lyrics not displaying in Quodlibet using the "View Lyrics" plugin) needs a separate, new issue opened, or if it is somehow related to this one.

I don't fully understand USLT in terms of ID tags, but my embedded lyrics are all in ID3 v2.3 format (which I believe is supposed to support USLT frames), and they display properly in many other Linux-based applications (Puddletag, gmusicbrowser, etc).  In Quodlibet, the "View Lyrics" tab just displays "No lyrics found for _`<file name>`_."  If I should open a new issue, please advise.  Thanks.

**Comment by frestr** [comment] 2018-10-12 05:13
> In Quodlibet, the "View Lyrics" tab just displays "No lyrics found for <file name>." 

Have you tried with the latest master? This should've been fixed in 03c3a0e741c79ed422b1dfb28b43e06c5bedd8d2 (see #2988), unless you are experiencing a separate issue.

**Comment by frestr** [comment] 2018-10-14 11:53
Setting up a dev enviroment as described in [the docs](https://quodlibet.readthedocs.io/en/latest/development/devenv.html) and running it from there should normally not cause any issues. I can't really give any "guaranteed to work" method.

**Comment by dannn-o** [comment] 2018-10-15 10:29
Thanks - I will take a look and see if I can use Git again to test the latest code, and report back.  Do I need to remove the installed version of Quodlibet (from the repository) before I install from the Git repositories?

**Comment by frestr** [comment] 2018-10-15 10:53
No, as long as you have the correct dependencies installed (which you most likely will if you're running a recent release) you can just run it directly from the repo (you don't need to install it).

**Comment by dannn-o** [comment] 2018-10-16 01:46
I am having difficulty getting the directions ([linked above](https://quodlibet.readthedocs.io/en/latest/development/devenv.html)) to work, and though I'm still trying to investigate I thought I'd post the symptoms here in case anyone spots what I might be 'doing wrong':

On my laptop running Mint 19, I added the unstable PPA (lazka/dumpingplace) and, after also installing Git, ran the clone command as documented, which appeared to complete successfully.  However, when executing the Python script in the subsequent line, this is the error that happens:

````
dan@ASUS-Mint:~$ ./quodlibet/quodlibet/quodlibet.py
Traceback (most recent call last):
  File "./quodlibet/quodlibet/quodlibet.py", line 15, in <module>
    sys.exit(main())
  File "/home/dan/quodlibet/quodlibet/quodlibet/main.py", line 28, in main
    quodlibet.init_cli(config_file=config_file)
  File "/home/dan/quodlibet/quodlibet/quodlibet/_init.py", line 133, in init_cli
    _init_formats()
  File "/home/dan/quodlibet/quodlibet/quodlibet/_init.py", line 112, in _init_formats
    from quodlibet.formats import init
  File "/home/dan/quodlibet/quodlibet/quodlibet/formats/__init__.py", line 10, in <module>
    from ._audio import PEOPLE, AudioFile, DUMMY_SONG, decode_value, \
  File "/home/dan/quodlibet/quodlibet/quodlibet/formats/_audio.py", line 36, in <module>
    from ._image import ImageContainer
  File "/home/dan/quodlibet/quodlibet/quodlibet/formats/_image.py", line 9, in <module>
    from ._misc import AudioFileError
  File "/home/dan/quodlibet/quodlibet/quodlibet/formats/_misc.py", line 13, in <module>
    import mutagen
ModuleNotFoundError: No module named 'mutagen'
dan@ASUS-Mint:~$ sudo apt-get install mutagen
[sudo] password for dan: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mutagen
````
The documentation indicated that all dependencies needed would be meet by installing the unstable repository?  Even when trying to install Mutagen manually as shown in the code after the initial error, apt-get is indicating it can't be found in any of the repositories (including the unstable PPA).  

Any advice??

**Comment by dannn-o** [comment] 2018-10-17 21:46
Well, I think I figured out the dependency issues and am posting this in case anyone else stumbles here looking for help.  For some reason, I had to manually install both Mutagen and Feedparser, and the commands I used (Linux Mint) were:
```
sudo apt-get install python3-mutagen
sudo apt-get install python3-feedparser
```
Afterward, I could launch Quodlibet (4.2 development version), and the View Lyrics plugin appeared to work successfully for 2 random albums from my music collection.  There do seem to be some display issues (for example, apostrophes being displayed as a box with a numeric code (unicode? UTF?), which would need to be pursued in a new issue, anyway,  if it is in fact a code problem.  But, the embedded lyrics do appear to be retrieved and displayed successfully.

**Comment by gypsyhut** [comment] 2018-10-27 02:31
Lyrics display issue is resolved, but multiline tags issue as described in this thread is not fixed. 

> We could add a hardcoded list of single value tags and handle them in a special way.

Instead, we should have a hardcoded list of multiline tags and handle them separately. There will be very few tags which are multiline i guess.

**Comment by crankedguy** [comment] 2022-02-12 12:11
Hello,

it seems that there was no progress on this since years. I have a huge problem here, as my library is around 7K releases.
I wrote my own tagging application for it as no one on the market was tailored enough. BUt my problem is generic here.
I have, like described before, some multiline tags like comment, description etc. We are talking FLAC (Vorbis Comments) here.
They are all separated with \n inside one tag, like it should be.
What happens now is that in the tag editor fields QL shows every line as a separate tag (eg comment, comment, comment...) and in the list view it is even more strange, as there all the lines are displayed but they are separated with a ,
e.g.
PROFILE=Founded in 1987\n
Created something...
turns into
Founded in 1987
, Created something 
in the main view.

Is there not a quit eeasy fix for that where you can define multiline fields and the \n-split rule is not applied there? 

Please get back to me as soon as you can as I have to look for another solution then. Retagging 7K releases is not a thing that is bearable here.

Many thanks.

**Comment by declension** [comment] 2022-03-15 22:01
> What happens now is that in the tag editor fields QL shows every line as a separate tag (eg comment, comment, comment...) 

Yes, this is because QL takes the opinion that \n delimits multi-valued tags. It works when it works...

> 
> Is there not a quite easy fix for that where you can define multiline fields and the \n-split rule is not applied there?

Yes this is probably the way to go, just needs to get done some time...
 

> Edit : Even stranger, sometimes the tag is displayed in one line, but also split with a , where there was a newline, so for the above example Founded in 1987., Created something

Yes, this is intended behaviour (known internally as `comma()`). It's used to present lists of multiple values to users in single-line or single-string contexts, e.g. for `artist` tag display, it might be _Aerosmith, Run DMC_

**Closed** 2022-03-18 20:25 UTC
Labels: enhancement
