### ISSUE TITLE
ReplayGain plugins resets tags (Ex Falso)

### ISSUE THREAD

**Issue by brenthuisman** [quodlibet/quodlibet#3095] opened 2018-12-30 14:31 UTC
Steps to reproduce
------------------

* Open Ex Falso
* Edit some tags in some m4a / mp3 files.
* Save/Apply tags.
* _Don't_ change directory
* Use the ReplayGain plugin to scan the files and save those results

Expected Output
---------------
Recent tag changes are saved

Actual Output
-------------
All changes seem to be reset to the state before I navigate to the files in Ex Falso. ReplayGain seems to take store the state upon navigating to a file somehow. This should not happen, nor should it touch any other tags in any case.

I did not save any, but happy to supply whatever is useful. 

Test System
-----------

### Which version of Quod Libet?
4.2.

### Which operating system 
Windows 10.

**Comment by CreamyCookie** [comment] 2019-06-22 16:12
I cannot reproduce this. Could do this again with 3 screenshots of the ExFalso window, one before the change, one after change (and save) and one after using the ReplayGain plugin? (with changed tags in view)

**Comment by brenthuisman** [comment] 2019-06-23 09:26
I just reproduced it again. It's quite simple, any change made but not explicitly saved before running replaygain is undone upon saving the RG result.

**Comment by CreamyCookie** [comment] 2019-06-23 09:31
Huh... Your third step was "Save/Apply tags."

**Comment by brenthuisman** [comment] 2019-06-23 09:40
Ah, don't know why I wrote that... Indeed, if you do save it explicitly first, it works as expected. It's just a bit unintuitive that this step is required. It's already quite hard to batch certain operations in Ex False, I guess this bothered me enough to write an Issue ;)

Your update to your post just popped in: in my view, all edits could be autosaved (or queued). I do understand not everybody wants that, so the autosave behavior could be a preference. (I imagine autosave is easier to implement than an edit queue).

**Comment by CreamyCookie** [comment] 2019-06-23 10:05
I think there's a bug for adding an option to always save, but I can't seem to find it. There's also one for adding a keyboard shortcut: #697

I'll close this in favor of #3197

**Closed by CreamyCookie** 2019-06-23 10:05 UTC
Labels: bug, needinfo
