### ISSUE TITLE
Playlist entries removed when files not accessible

### ISSUE THREAD

**Issue by Konzertheld** [quodlibet/quodlibet#1733] opened 2015-11-05 16:29 UTC
When files are hidden because they have been removed or the volume they are on has been unmounted, the tracks are removed from all the playlists they are on and do not re-appear when files are unhidden.

**Comment by declension** [comment] 2015-11-18 20:07
See #518

**Comment by CreamyCookie** [comment] 2019-07-24 09:36
Actually, I think this is a duplicate of #708: Playlists should recover from missing media  (Feel free to reopen if I'm mistaken.)

**Closed by CreamyCookie** 2019-07-24 09:36 UTC
Labels: bug
