### ISSUE TITLE
error to refresh library on start

### ISSUE THREAD

**Issue by NicoleSharpFrostburg** [quodlibet/quodlibet#1867] opened 2016-02-29 15:06 UTC
Quod Libet 3.5.2 frequently crashes on Microsoft Windows 10 Pro 64-bit when "Music" / "Preferences" / "Library" / "Scan Directories" / "Refresh library on start" is set.  Turning off "Refresh library on start" seems to resolve the issue.  The same or a very similar bug on Windows 7 is also listed here: < [http://www.github.com/quodlibet/quodlibet/issues/1696/](http://www.github.com/quodlibet/quodlibet/issues/1696/) >.  The pop-up error message reads:

Microsoft Visual C++ Runtime Library

Runtime Error!

Program C:\Program Files (x86)\Quod Libet\bin\quodlibet.exe

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by NicoleSharp** [comment] 2016-02-29 16:28
I am also getting the same crash and error now on any attempt to refresh the library.  I removed the directories, uninstalled Quod Libet, and manually deleted "C:\Users\Nicole\AppData\Roaming\Quod Libet".  After reinstalling and rebuilding the library from scratch, I seem to be back to the original problem above.

**Comment by lazka** [comment] 2016-02-29 17:43
Thanks for the report. It's probably the same problem as #1696. Based on your description could it be that it only occurs in cases a library scan does not result in newly added songs?

**Comment by NicoleSharpFrostburg** [comment] 2016-02-29 19:07
No; I had recently added tracks to my music directory when it began crashing upon any attempt to refresh, as opposed to just refreshing automatically upon start.

**Comment by lazka** [comment] 2016-03-03 18:09
Could you try the newest build?

https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.6.-1-rev7983-3f0fb55-installer.exe
https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.6.-1-rev7983-3f0fb55-portable.exe

**Comment by lazka** [comment] 2016-03-04 14:33
Closing as a duplicate of #1696, feel free to continue posting here or there. Thanks.

**Closed by lazka** 2016-03-04 14:33 UTC
Labels: bug, needinfo, windows
