### ISSUE TITLE
Internet Radio browser doesn't support PLS files with non-matching case

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1536] opened 2015-03-15 01:10 UTC
Original [issue 1536](https://code.google.com/p/quodlibet/issues/detail?id=1536) created by toupeira23 on 2015-02-11T09:16:50.000Z:

<b>\- What did you try to do?</b>
1. Open Internet Radio browser
2. Add a new station using the URL http://somafm.com/secretagent130.pls

<b>\- What did you expect to happen?</b>

The playlist should be parsed and the three URLs added as new stations.

<b>\- What did happen instead?</b>

I get an error message &quot;No stations found&quot;. If I edit the file to change the File1/Title1/Length1 keys to lowercase, the playlist is parsed successfully.

<b>\- Which version of Quod Libet?</b>

3.2.2-1, but I also checked browsers/iradio.py in trunk which still expects lowercase keys in the ParsePLS() function.

<b>\- Which operating system including version (Ubuntu 14.04, Win7, Debian</b>
<b>sid)?</b>

Debian sid

**Comment by declension** [comment] 2020-02-23 22:39
Can't reproduce this (that URL adds fine), and on inspection [the code definitely lowercases the key](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/browsers/iradio.py#L152), so closing.

**Closed by declension** 2020-02-23 22:39 UTC
Labels: bug
