### ISSUE TITLE
Quod Libet/Ex Falso always create quodlibet::albumartist tag

### ISSUE THREAD

**Issue by jberli** [quodlibet/quodlibet#3202] opened 2019-07-02 16:18 UTC
I don't know if this is actually an issue or if it's me, but whenever I add an albumartist tag to a bunch of files, it creates the tag as an Quod Libet specific tag. For instance, when I check the files with MusicBrainz Picard, it appears as QuodLibet [:albumartist], same with VLC.

albumartist is supposed to be a generic tag, I'm wondering how can create them accordingly as I need to use a sample of my library with iTunes to synchronize it on a portable device.

Thanks in advance, and thanks for that awesome music player !

**Comment by CreamyCookie** [comment] 2019-07-24 15:37
This only happens for mp3 as far as I know, so I'm closing this as a duplicate of #1179.

There's also a pull request for closing it: #2592

**Closed by CreamyCookie** 2019-07-24 15:37 UTC
