### ISSUE TITLE
Number of songs not showing correctly in paned browser

### ISSUE THREAD

**Issue by NjaalBendixen** [quodlibet/quodlibet#2348] opened 2017-03-29 18:55 UTC
Hi All

I am a tango dj, and I use QuodLibet since it is the only program that allows me to define my own tags. Thank you very much for this magnificent software.

One thing does not work as intended though. It used to work in the past, several years ago, but now never works on any machine that I use.

Please excuse my lack of technical language, I am not a programmer, I am only a user.

In the paned browser the filter fields I choose which tags to use as criteria. so for example the genre tag is used and I can see how many songs I have in each genre. However I can not see all the digits of the number of songs. For example I have 2025 tangos, but in the paned browser I can only see (20

therefore I do not know if I have 20, or 200 or 2000 tangos.

This is a really big problem for me if I am djing live and I have 20 seconds to choose the next song.

I now use a Macbook pro mid 2010, 2.4gh with Linux mint 18.1 KDE installed on it in single boot mode.

In the resent past (last 5 years) I have used linux mint and ubuntu on various pcs and I had the same problem. More than 5 years ago I did not have this problem and quodlibet always showed the correct number of songs nicely.

Please see a screenshot of my problem

![screenshot_20170329_205358](https://cloud.githubusercontent.com/assets/25297408/24471276/ef408432-14c1-11e7-8fe6-7dc2e9260514.png)

**Comment by lazka** [comment] 2017-03-29 19:17
Thanks. Duplicate of #1750

**Closed by lazka** 2017-03-29 19:17 UTC
