### ISSUE TITLE
 Wrong cover pictures shown 

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2557] opened 2017-09-06 10:17 UTC
See https://groups.google.com/forum/#!topic/quod-libet-development/ual2XnbUBSA

I couldn't reproduce, but needs another look to be sure.

[grimm_ruhrpott_sterntaler.zip](https://github.com/quodlibet/quodlibet/files/1280709/grimm_ruhrpott_sterntaler.zip)

**Comment by urielz** [comment] 2017-10-04 14:50
I can't reproduce either.

**Comment by CreamyCookie** [comment] 2019-06-22 19:02
Cannot reproduce either. Closing.

**Closed by CreamyCookie** 2019-06-22 19:02 UTC
