### ISSUE TITLE
Make Playlist Browser persist the user-defined order of its playlists

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1645] opened 2015-07-02 14:56 UTC
> If I create a few playlists, they appear in the playlist browser in
> the order they are created. If I close QL and restart it, the
> playlists appear in alphabetical order in the browser.

See https://groups.google.com/forum/#!topic/quod-libet-development/i9tzsT8U0Lo

**Comment by will-ca** [comment] 2019-02-17 04:26
They are reorderable and the order does persist though?

Click-and-drag on the items reorders them, and the new order is reflected instantly in `~/.quodlibet/playlists`.

**Comment by declension** [comment] 2019-02-17 09:59
@will-ca this is a confusing title / issue. I've edited the original to include the quote and will find a better title

**Comment by declension** [comment] 2020-11-28 11:45
Can't reproduce the original bug, and the bigger issues are tracked elsewhere, so closing

**Closed by declension** 2020-11-28 11:45 UTC
Labels: browsers, enhancement, playlists
