### ISSUE TITLE
Not saved settings of windows

### ISSUE THREAD

**Issue by TombusPL** [quodlibet/quodlibet#1959] opened 2016-05-28 17:01 UTC
QL not save position of window if it is left side (hard coded minimum length of buttons?)

movie:https://www.youtube.com/watch?v=mfVDvdWvkiU

This same is about queue.
If queue is empty and set position after exit queue is closed.

QL 3.6.2

**Comment by lazka** [comment] 2016-05-28 17:15
Thanks

**Comment by d9h02f** [comment] 2016-06-06 17:59
https://github.com/quodlibet/quodlibet/issues/1605

**Comment by lazka** [comment] 2016-08-01 06:34
I can't reproduce, but probably fixed by a8bb9ee28c0f2

**Closed by lazka** 2016-08-01 06:34 UTC
Labels: bug
