### ISSUE TITLE
Strange playback behaviour

### ISSUE THREAD

**Issue by wennaspeedy** [quodlibet/quodlibet#4320] opened 2023-06-05 09:50 UTC
Steps to reproduce
------------------

Now I double click an album and it starts playing the first song from the album and after playing the first song it jumps to the queue. This is strange and illogical behavior. Just like if I stop a song with the space key and press space again, it jumps from the queue to the open album

Expected Output
---------------
I would expect a double click to add the album to the queue and start playing if the queue is empty, as is the case with other players.

**Comment by jej** [comment] 2023-06-05 11:12
Personally the queue and playing behaviour is the last reason I have to use quodlibet :)) But agree that it's a topic opinionated and depends a lot of personal approach concerning music listening...

**Comment by declension** [comment] 2023-06-08 17:31
This sounds like a duplicate of #3959, so closing in favour of that one

**Closed by declension** 2023-06-08 17:31 UTC
Labels: bug
