### ISSUE TITLE
Allow multiple copies of a song in a playlist

### ISSUE THREAD

**Issue by joshtriplett** [quodlibet/quodlibet#2662] opened 2017-12-22 22:25 UTC
It should be possible to create a playlist that contains multiple copies of the same song.

Right now, Quod Libet assumes that a playlist will contain exactly one instance of a song; manually editing a playlist to add a second copy creates *interesting* behavior, such as skipping the current position to the second instance when the first is played.

**Comment by declension** [comment] 2017-12-23 05:42
This is already possible - in fact this is the reason there's a _Remove Duplicates_ playlist plugin among other things.

There is some known behaviour captured in another ticket around playlist duplicates, I'll try to dig out the number.

If you're not seeing this though, it's a regression... so please post environment details and steps to reproduce, and we can investigate.

**Comment by joshtriplett** [comment] 2017-12-23 08:09
I'm seeing this on latest Debian unstable:
```
~$ quodlibet --version
Quod Libet 3.9.1
<quod-libet-development@googlegroups.com>
Copyright 2004-2017
```

If I right-click on a song that's already in a playlist, I get a checked checkbox for that playlist, and choosing that removes it rather than adding it. If I close Quod Libet, edit a playlist with a text editor, duplicate a line (e.g. add a copy of the first song as the last song), then reopen Quod Libet, the duplicate shows in the playlist UI, but if I choose to play the playlist, when Quod Libet goes to play the first copy, the "play" icon appears next to the second copy instead, and when it's done playing that one it continues from there.

**Comment by declension** [comment] 2017-12-23 21:18
See (slightly) related #1897

**Comment by declension** [comment] 2017-12-24 11:45
> If I right-click on a song that's already in a playlist, I get a checked checkbox for that playlist, and choosing that removes it rather than adding it.

This bit is intended behaviour BTW - this browser was developed with the primary use-case of playlists as ordered (or unordered) collections of tracks without duplicates, and the context menus are optimised for this case, i.e. quickly adding and removing songs across playlists.

That said if you have ideas for an improvement for that UX around handling duplicates (that remains compatible with the current use-cases) please raise a new issue - e.g. see #1059 for how that context menu last got extended.

>  If I close Quod Libet, edit a playlist with a text editor, duplicate a line (e.g. add a copy of the first song as the last song), then reopen Quod Libet

FYI an easier way here to add (duplicate) songs is to drag-and-drop from one songlist onto the playlists items browser (i.e. the left panel in that browser) or onto the songlist of the selected playlist. Another, less known / intuitive way is to drag one playlist itself onto another to add _all_ those songs.

>  when Quod Libet goes to play the first copy, the "play" icon appears next to the second copy instead, and when it's done playing that one it continues from there.

Yes this sounds like something that should be fixed. I can't reproduce this though on latest git `master` (a2998ac21859e925807cb54d27faaede0c5930fa). Will try to have another go on another machine / setup in a few days though.

**Comment by CreamyCookie** [comment] 2019-06-25 15:04
#1651 would also help for adding a song multiple times.. 

I personally really like the check mark playlist feature (remove mark for removing from playlist) and use it all the time. I'm also not sure how often people add duplicates to their playlist.. 

> Yes this sounds like something that should be fixed. I can't reproduce this

Also can't reproduce. I'm closing this one since the the main feature request is already fixed and the bug seems to be gone in more recent versions.

**Closed by CreamyCookie** 2019-06-25 15:04 UTC
