### ISSUE TITLE
POPM-tags are not reloaded when the library is updated/reloaded

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#515] opened 2015-03-14 22:45 UTC
Original [issue 515](https://code.google.com/p/quodlibet/issues/detail?id=515) created by dany@timra.se on 2010-05-23T11:27:36.000Z:

Prerequisites:

The newest  unstable version of QL from launchpad

dpkg --list|grep 'quodlibet|mutagen'

ii  python-mutagen                        1.19.99-0~rev86~ppa1~lucid                      audio metadata 
editing library
ii  quodlibet                             2.2.99-0~rev4488~fff1f4bd3d9f~ppa1~lucid        audio library 
manager and player for GTK+
ii  quodlibet-plugins                     1:2.2.99-0~rev4470~3f517469094c~ppa1~lucid      various 
contributed plugins for Quod Libet
# 

Steps to reproduce:

1) Set the rating of any song in QL and write the tag to the file using the &quot;Force Write&quot;-plugin. 
Check that the POPM-tag is written by using mid3v2.

2) Use Picard to change the rating and the song name. Use mid3v2 and make sure the tags 
has been written properly.

3) Choose &quot;Update library&quot; or &quot;Reload library&quot; from the file menu in QL

4) The song name but not the rating is updated in QL

5) Delete the song from the library (do not delete the file)

6) Choose &quot;Update library&quot; or &quot;Reload library&quot; from the file menu in QL

7) The song name AND the rating are updated in QL
# 

Expected results:

1) The rating should be reread from the file in step 4 above.
# 

Comments:

In principle it is possible to reread the tags from all files by deleting all songs from the library 
(steps 5-7), but this is very inpractical since all playlists will be destroyed.

**Comment by CreamyCookie** [comment] 2019-06-22 10:10
Closing as intended. There's also the [Auto Library Update plugin](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/events/auto_library_update.py)

There's also #1039 for making Auto Library Update plugin part of the base.

**Closed by CreamyCookie** 2019-06-22 10:10 UTC
Labels: bug
