### ISSUE TITLE
Move non-art files (e.g. log/cue, lineage.txt) option in rename files dialogue

### ISSUE THREAD

**Issue by rudluff** [quodlibet/quodlibet#3359] opened 2020-04-26 21:52 UTC
The proposed change
-------------------
Currently, QL abandons all albumart other than the one it identifies as cover.jpg (even if "move art" is checked), as well as files like log/cue, lineage.txt, an album m3u, and other miscellania. QL should have an option to move these.

Benefits of this change
-----------------------
Sometimes data held in these other files is important. For example, most cue files have the discid in them, allowing later lookup of the disc if you should desire to populate edition-related fields; a log file can be parsed to determine whether this is a "perfect" CD rip or whether you need to rip it again, albumart other than cover.ext is nice, yadda yadda.

Any issues this might cause
---------------------------
1. It is impossible to guess what miscellania files are useful to which people, so some kind of mechanism to allow the user to manually specify would be needed (perhaps by suffix only); as in any field the user is allowed free input, disastrous user error in these fields could result in hilarious consequences.

2. Multi-disk albums usually have multiple log files; if moving files to multiple directories (e.g. from one mega-album directory to disk 1/ and disk 2/) QL would have to do some fuzzy matching to guess which is which because users are "smart". Likewise, if moving files from multiple folders to one master folder, it might result in disaster when it turns out all the log files have the same filename (just like "album title.log") but are intended for multiple disks, and QL has to haphazardly guess how to name logs.

**Comment by declension** [comment] 2020-04-27 07:50
Is this a duplicate of #2751?

**Comment by rudluff** [comment] 2020-04-27 19:12
Ooh, you're right. Still hacky to have to put log and cue and etc. as image extensions, but at least it kinda works. (altho attempting to move log/cue into correct folder is still somewhat of a pipe dream :-)
     On Monday, April 27, 2020, 03:50:35 AM EDT, Nick Boultbee <notifications@github.com> wrote:  
 
 


Is this a duplicate of #2751?

**Comment by CreamyCookie** [comment] 2021-04-19 10:00
Closing as a duplicate of #2751 (which still open as of this time).

Still, thanks for reporting the issue!

**Closed by CreamyCookie** 2021-04-19 10:00 UTC
Labels: enhancement
