### ISSUE TITLE
Quod Libet g-io-error-quark: Socket I/O timed out (24)

### ISSUE THREAD

**Issue by Dickerson-Web-Consulting** [quodlibet/quodlibet#2246] opened 2017-02-18 02:31 UTC
I am running Quod Libet 3.5.3, under Xubuntu 16.04  (AMD64) with a first-generation Intel Core i7 quad-core processor and 16GB of 1333 RAM, and the 'Error Occured' error window appeared.

Quod Libet is still running but the application error advises that it may be unstable: "Closing and restaring is recommended. Your library will be saved."

I have been running an rsync session in the background, and I have very limited bandwidth via a USB toggle connection to an Android 6.1 smart phone, which is causing other problems, including very slow (worse than v.90 dial-up, literally) -- a detail that may or may not be at the crux of this error.

Below is the dump (MiniDump) file from my local .quodlibet directory.

Cordially,

David

--

[MiniDump_20170217_193638.txt](https://github.com/quodlibet/quodlibet/files/784710/MiniDump_20170217_193638.txt)

**Comment by lazka** [comment] 2017-02-18 08:09
Thanks

**Comment by lazka** [comment] 2017-02-18 08:15
If it happens often your can disable the cover source plugins.

not related to this error, but if you want a newer quodlibet, check out our PPA: https://quodlibet.readthedocs.io/en/latest/downloads.html#ubuntu

**Comment by declension** [comment] 2017-02-20 12:05
Related: #1752

**Comment by declension** [comment] 2017-11-01 08:16
Duplicate of (now solved #2590)

**Closed by declension** 2017-11-01 08:16 UTC
Labels: bug
