### ISSUE TITLE
Copy album art (folder.jpg\cover.jpg) when copying\renaming files

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#237] opened 2015-03-14 22:07 UTC
Original [issue 237](https://code.google.com/p/quodlibet/issues/detail?id=237) created by still.ryan on 2009-06-23T18:56:28.000Z:

It would save a lot of time for people who use one album art image instead
of embedded album art if you were able to copy the relevant (or
user-defined) image file to the destination directory alonb with the music
files.

**Comment by CreamyCookie** [comment] 2019-06-22 19:17
Closed as a duplicate of the clearer and more general (not just album art) #2751.

**Closed by CreamyCookie** 2019-06-22 19:17 UTC
Labels: enhancement
