### ISSUE TITLE
Selecting arrays in lists with Ctrl+Shift

### ISSUE THREAD

**Issue by Socialdarwinist** [quodlibet/quodlibet#2479] opened 2017-07-14 21:55 UTC
Desired behavior:
I select selectively with Ctrl, and put rows into my selection by Ctrl+Shift. Like when I have an array {1,2,3,4,5,6,7,8,9,10}, I click 2 to select it, then I ctrl+click 4 to have selected 2 and 4, then ctrl+shift+click 8 to have 2 and 4–8 selected. This works in all good file managers and bookmark folders in browsers.

Actual behavior: 2 and 4 and 8 is selected, not also 5, 6 and 7.

Implementing this behavior would substantially increase efficiency of usage. Right now one has, for instance, to remove pieces of an album from a playlist to select them one by one or to search them first in another browser to remove them alltogether.

I am using Quod Libet on Cinnamon on Arch Linux.

**Comment by CreamyCookie** [comment] 2019-07-24 14:43
Closing this as a duplicate of #3227 

It's a bit newer but uses the new template and I found it a bit more clear. I added part of your description though. Thanks for the report!

**Closed by CreamyCookie** 2019-07-24 14:43 UTC
