### ISSUE TITLE
Incorrect track number sort order

### ISSUE THREAD

**Issue by severoraz** [quodlibet/quodlibet#2182] opened 2017-01-05 21:09 UTC
I have a group of files with track numbers from 1 to 58, some of which are repeated. When I sort by track number in ascending order, tracks 48 and 49 appear at the top, and afterwards tracks are correctly ordered from 1 to 58. Needless to say, tracks should be ordered all from 1 to 58.

What other information can I provide to help solve this issue?

**Comment by lazka** [comment] 2017-01-11 18:20
When sorting by track we first sort by album and then by track because that's what you usually want in that case.

**Comment by ned2** [comment] 2017-01-13 02:25
Actually @declension @lazka, I think there might be a regression from 88261cf29abd46a2ab481902713f3225b5563fa5. After this commit, running from master branch gives me broken sort order when sorting on track number. Can't tell what it's actually sorting on, but it's consistent.

**Comment by declension** [comment] 2017-01-13 08:01
@ned2 interesting, but sounds like a separate problem - the OP filed this issue before that commit was made. Could you open a new bug, if possible with steps to reproduce?
Thanks.

**Comment by declension** [comment] 2017-01-13 17:36
It's OK - we've got one now #2182

**Comment by ned2** [comment] 2017-01-14 01:28
Ah, didn't check the date stamp closely enough. Nice work on the speedy fix :)

**Comment by severoraz** [comment] 2017-01-20 21:18
@urielz yes all tracks are using tracknumber field, none of them are using track field.

@lazka I'm afraid in this case I am only concerned by track number, however all tracks have the same album too.

**Comment by severoraz** [comment] 2017-03-25 11:14
@declension so is this bug solved now as issue #2196?

**Comment by declension** [comment] 2017-03-26 18:04
I think so @severoraz, but please re-test on latest a recent build

**Comment by severoraz** [comment] 2017-08-12 11:22
I have installed quodlibet-git-r9341.e100ed7d7-1 (v 3.10.-1 according to the About), which pacaur tells me is current as of 2017-08-12T13:13+0200, and it unfortunately it still has the problem.

**Comment by RafaelFrance** [comment] 2019-05-26 14:21
Is it possible when sorting tracks to sort only by tracks, not sorting first album ?
It is not natural to sort by another tag.

**Comment by CreamyCookie** [comment] 2019-06-22 14:48
This might be the same issue as #3179 (only with a different tag instead of the `track` number)

@severoraz Could you upload a screenshot of the affected album (with columns like Disk num visible)?

**Comment by CreamyCookie** [comment] 2019-07-21 20:47
Closing as incomplete.

**Closed by CreamyCookie** 2019-07-21 20:47 UTC
Labels: needinfo
