### ISSUE TITLE
Couldn't find module 'soco'

### ISSUE THREAD

**Issue by timkgh** [quodlibet/quodlibet#3802] opened 2021-09-11 18:25 UTC
Steps to reproduce
------------------
Go to plugins, click "Show Errors"

Expected Output
---------------
No errors by default, I do not use Sonos, it should not be looking for it.

Actual Output
-------------
Sonos error even though I don't use it.

Test System
-----------

### Which version of Quod Libet?
4.4.0

### Which operating system 

macOS Catalina

### If it's audio-related, what back-end?

Additional Information
----------------------
Error
```
export_to_sonos
Couldn't find module 'soco'. Perhaps you need to install the package?
```

**Comment by declension** [comment] 2021-09-12 08:45
This is expected behaviour currently - the plugin errors window reports _everything_ that caused exceptions in loading the modules for all plugins, and typically plugins import the modules they need globally.  (Agree that this is a bit confusing though - perhaps not calling them _errors_ would help?)

For example, on this machine I get `paho-mqtt` and `kakasi` missing too
![Screenshot from 2021-09-12 09-40-37](https://user-images.githubusercontent.com/3322808/132980185-c11033da-e1b8-437a-9867-34e28e657d4c.png)
I guess you must have these packages (and others installed) - it might be that these optional(ish) packages were installed but not `soco`, due to MacOS packaging not including this recently added optional dependency perhaps.

**Comment by zeezhao** [comment] 2021-11-09 12:31
Hi. The "export_to_sonos"/"soco" message is the same error on windows10 though. So maybe a cross-platform issue.

**Comment by declension** [comment] 2021-12-29 13:56
From the above this is just expected behaviour, so closing for now

**Closed** 2021-12-29 13:56 UTC
Labels: bug, plugins

**Comment by Heavygrass** [comment] 2025-06-20 20:57
We need some documentation on whats the corresponding names for paho-mqtt, soco, kakasi, pypresence in popular Linux distros (e.g. Ubuntu, Mint).

Ubuntu generally doesn't allow to simply use `pip install`:
`pip install paho-mqtt`
`error: externally-managed-environment`.

`pipx install paho-mqtt`
`No apps associated with package paho-mqtt or its dependencies. If you are attempting to install a library, pipx
should not be used. Consider using pip or a similar tool instead.`

I installed python3-paho-mqtt and kakasi, kakasi-dic in Ubuntu and its still giving the same errors.
There's 5 kakasi related packages in Ubuntu:
`kakasi-dic/noble,noble,now 2.3.6-4.1 all [installed,automatic]`
`kakasi/noble,now 2.3.6-4.1 amd64 [installed]`
`libkakasi2-dev/noble 2.3.6-4.1 amd64`
`libkakasi2/noble 2.3.6-4.1 amd64`
`libtext-kakasi-perl/noble 2.04-5build5 amd64`
`ruby-kakasi-ffi `

How does one know what to install?

For soco there's only these packages:
`librust-isocountry-dev/noble 0.3.2-1 amd64`
`r-cran-isocodes/noble,noble 2024.02.12-1 all`

Are they even relevant?
