### ISSUE TITLE
Progressbar appears in the top left corner of the screen

### ISSUE THREAD

**Issue by felixhofer** [quodlibet/quodlibet#1912] opened 2016-04-09 20:04 UTC
The progressbar appears in the top left corner of screen when its opened. 
It should come in beside the time display.

This issue first occured after upgrading gtk to version 3.20.
I'm using Quod Libet 3.5.1 on Arch Linux.

**Comment by lazka** [comment] 2016-04-10 05:26
That's a regression in gtk+ 3.20.2, should be fixed in 3.20.3.

**Comment by lazka** [comment] 2016-04-10 10:53
Also QL 3.5 has various issues with gtk+ 3.20 which are fixed in 3.6, but there is #1906 ...

**Comment by gui-don** [comment] 2016-04-12 09:19
Same thing with the notification plugin (cf: screenshot). Should be “Bottom of the screen”.

I guess it’s gtk+ too.

![capture d ecran de 2016-04-12 11-14-55](https://cloud.githubusercontent.com/assets/1037958/14455501/2156a2da-00a0-11e6-9493-119b76acc867.png)

**Comment by lazka** [comment] 2016-04-12 09:24
yeah... 3.20.3 was released yesterday so it should end up in Arch etc. shortly.

**Comment by felixhofer** [comment] 2016-04-12 20:50
The progressbar bug was resolved with the gtk+ update to 3.20.3. Another thing i noticed is the play queue doesn't adjust its height. This issue also exists in the development version.
![screenshot from 2016-04-12 22-44-16](https://cloud.githubusercontent.com/assets/9267733/14475106/96faae7c-0100-11e6-9717-ff3012e92cab.png)

**Comment by lazka** [comment] 2016-04-13 03:41
Uh :/ I'll have a look, thanks.

**Comment by Jimi-James** [comment] 2016-04-15 20:33
Oh, looks like I opened #1915 for nothing. That's crazy that I found these comments. I was literally just clicking through looking at issues that reference the Arch package not being updated.

**Comment by lazka** [comment] 2016-04-16 13:48
Let's continue in #1915

**Closed by lazka** 2016-04-16 13:48 UTC
Labels: upstream-bug

**Comment by ewtoombs** [comment] 2016-07-06 22:20
This has been driving me crazy. Anybody know what's going on with this bug?
