### ISSUE TITLE
Horizontal scaling cursor is vertical.

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#1945] opened 2016-05-16 15:28 UTC
![http://imgur.com/heqqVmv](http://i.imgur.com/heqqVmv.png)

Look at the cursor. I guess it's self-explanatory.

Edit: Sorry, I forgot my setup:
```$ quodlibet -v
Quod Libet 3.7.-1
<quod-libet-development@googlegroups.com>
Copyright © 2004-2016 Joe Wreschnig, Michael Urman, Iñigo Serna, Steven Robertson, Christoph Reiter, Nick Boultbee...```
```$ uname -a
Linux peter-Lenovo-G580 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by urielz** [comment] 2016-05-16 15:44
I can't reproduce this on QL 3.6.1 OS X.

**Comment by lazka** [comment] 2016-05-16 16:51
Ubuntu 14.04?

**Comment by lazka** [comment] 2016-05-20 15:24
I can't reproduce on 14.04 (Unity default..). Maybe a problem with a cursor theme? Closing for now..

**Closed by lazka** 2016-05-20 15:24 UTC
Labels: needinfo
