### ISSUE TITLE
Cover grid scroll performance

### ISSUE THREAD

**Issue by slosd** [quodlibet/quodlibet#2840] opened 2018-05-09 19:02 UTC
I experience severe performance issues in the cover grid browser when I'm scrolling through the albums.

This only happens when I'm **not** using gnome-shell and it happens with or without a desktop session, with several different window managers (tried Mate's marco, awesomewm, xmonad).

Applying [this changeset](https://github.com/quodlibet/quodlibet/pull/2481/files#diff-725a1363e50790bee2c8cd9a7aff8ded) proposed in a pull request fixes the scroll performance issue.

> openSUSE Leap 42.3
> QuodLibet 4.0.2
> 
> Audio device: GStreamer (pulsesink)
> Python: 3.5.4
> Mutagen: 1.40.0
> GTK+: 3.20.10 (X11)
> PyGObject: 3.27.1
> GStreamer: 1.8.3.0
> 
> with proprietary nvidia driver v390.48

**Comment by lazka** [comment] 2018-05-15 16:32
Problem is that with the patch the view is unusable with GS here, so we need a different solution.

**Comment by lazka** [comment] 2018-05-15 18:14
I can't reproduce with xfce (with and without compositing) and openbox.

**Comment by KoO-303** [comment] 2018-06-27 11:47
I also have this with gnome and xfce. Very sluggish especially after first opening Quodlibet but does get faster as time goes by.Never quiet right though .With version 3 too.
Linux Debian Manjaro Antergos

**Comment by slosd** [comment] 2018-06-29 22:47
I've been trying to figure out what impact the callbacks of the cell renderers used for the items in the cover grid have: 
https://github.com/quodlibet/quodlibet/blob/36ef24bb56bd0b3b301a912b2bc696398313bff6/quodlibet/quodlibet/browsers/covergrid/main.py#L249 https://github.com/quodlibet/quodlibet/blob/36ef24bb56bd0b3b301a912b2bc696398313bff6/quodlibet/quodlibet/browsers/covergrid/main.py#L277

These are called **very** frequently and I think, potentially, this is an issue. Here are my results **with 1416 albums** in the cover grid. Unfortunately the data is just from one run per version and chart, so no averages. Each chart shows the number of calls per album with the changes I mentioned in my initial post applied ("patch") as well as without ("nopatch"). The charts only show the data for the first 100 albums because there is no change for albums beyond it. 

First, as a baseline, these are the calls (y-axis) per album (x-axis) after starting quodlibet and letting the cover grid browser initialize:
![calls_starting_ql](https://user-images.githubusercontent.com/99086/42117181-8c2af6dc-7bfb-11e8-8212-bde4d2c9db76.png)
patch total: 25579 calls
nopatch total: 17076 calls

These are the calls per album after starting quodlibet and letting the cover grid browser initialize and then scrolling down a bit:
![calls_scrolling_ql](https://user-images.githubusercontent.com/99086/42117248-da5f8c28-7bfb-11e8-80e0-92425f4fe691.png)
patch total: 26162 calls
nopatch total: 59754 calls


There are two observations here:
 - The number of calls in general seem pretty high. 
 - The number of calls in the second chart are much lower in the patched version. 

I don't know yet what to do with this information, if this is the reason the patch improves performance for me and if it is actually relevant to the performance issues others and I myself are experiencing.

**Comment by slosd** [comment] 2018-07-01 10:38
Just two more comparisons with the Album List browser:

![calls_starting_ql_2](https://user-images.githubusercontent.com/99086/42133487-5b817728-7d2b-11e8-8717-513b9f80c375.png)

![calls_scrolling_ql_2](https://user-images.githubusercontent.com/99086/42133488-5f9d445e-7d2b-11e8-83a4-750a15f27e15.png)

**Comment by Sabilon** [comment] 2018-07-29 20:52
In my case, the GUI is responsive in cover grid view just after Quodlibet is started. Then, if I filter albums with some text in the search field, then clear it, the GUI gets very sluggish (not only scrolling, the whole GUI, for example menus and buttons).

Then, if I switch to another view, say "Album list", and back to cover grid, the GUI gets responsive again.

Same behaviour in Quodlibet 3.9 (deb repositories) and 4.1 (flatpak). 

(~15000 songs / 1000 albums in my library. Linux Mint 19. i3 1.8GHz 8Gb RAM.)

**Comment by Hochiss** [comment] 2018-09-27 19:08
Can confirm the issue with very slow scrolling in cover grid browser within MacOS 10.13.2. Really prefer this can be solved, because Quod Libet is almost the only player capable of DTS music (no matter of digital outputs). thanks!
Quodlibet 4.1.0(MacOS 10.13.2) / CPU i7-8550U/16G RAM

**Comment by slosd** [comment] 2018-10-30 15:51
> If anyone's still experiencing slow performance on non-gnome-shell systems, can you try the updated changeset in #2481 again?

That fixes it completely for me.

**Comment by RedSofaForEveryone** [comment] 2019-04-27 21:12
This is an issue with Mac Mojave. Version 4.2.1.
30 album covers and it moves painfully slow.

**Comment by BenjaminLawson** [comment] 2020-02-22 17:13
This is still an issue on MacOS 10.14.5, Quodlibet 4.3.0 (just released). 401 album covers and scrolling has about a 3 second latency.

**Comment by howels** [comment] 2020-04-14 12:34
Same issue here. Scrolling the album covers takes 100% CPU even with a small number of albums.

**Comment by Meriipu** [comment] 2020-07-27 19:16
Never used the covergrid browser until today. It is incredibly sluggish when scrolling for me too.

**Comment by everdred** [comment] 2021-01-03 07:25
I'm not a developer but is there any way I can help diagnose this issue? This is my favorite view but it's basically unusable... with my library, simply switching back to QL from another application takes a very consistent five seconds to draw the window contents, and after it's loaded, scrolling through album covers in this view can either be instant or crushingly laggy with no apparent reason for one behavior or the other.

**Comment by Sabilon** [comment] 2021-01-04 06:10
@everdred : we might start by narrowing the conditions that trigger the issue. In https://github.com/quodlibet/quodlibet/issues/2840#issuecomment-408705069, I described these conditions, which are consistent on different computers and systems I own. It has not changed until then. Now I use Linux Mint 20 / Quodlibet 4.3 flatpak.

Do you experience the issue after the same steps as I do ?

**Comment by howels** [comment] 2021-01-13 13:12
I didn't need to use filter - the cover art grid view was unresponsive on startup and nothing changed that. I am now using gmusicbrowser which works fine.

**Comment by twirlip** [comment] 2021-02-24 19:25
> In my case, the GUI is responsive in cover grid view just after Quodlibet is started. Then, if I filter albums with some text in the search field, then clear it, the GUI gets very sluggish (not only scrolling, the whole GUI, for example menus and buttons).
> 
> Then, if I switch to another view, say "Album list", and back to cover grid, the GUI gets responsive again.

I'm experiencing exactly this behavior with current master, as well as with 4.3.0 installed via Flatpak. The cover grid works fine on startup, but after doing a search/filter the GUI becomes slow.

Ubuntu 20.04, i5-6200U CPU @ 2.30GHz × 4, 16GB RAM. Library has >1,900 albums and >16,000 songs.

**Comment by everdred** [comment] 2021-03-03 02:36
@Sabilon 

> Do you experience the issue after the same steps as I do ?

I finally got around to trying the exact steps you mentioned in this order and I can confirm that I saw identical behavior.

Having observed this in actual use for a while, I don't feel like I can consistently predict when lag will occur. (For instance, I have definitely also seen lag begin at the launch of the application.)

I've used this same QL library and application version (4.3.0) on both an i5-3230M CPU @ 2.60GHz and an i5-8365U CPU @ 1.60GHz, both with 16 GB RAM running Debian. While the lag periods tend to be shorter on the latter system, they're still very significant.

(I actually just noticed that 4.4.0 has been released! Looking forward to giving that a try once a Debian package is available.)

**Comment by Sabilon** [comment] 2021-03-03 23:02
Version 4.4.0 does not fix the problem here. Same behaviour observed (Flatpak, Linux Mint 20.1).

**Comment by darthoctopus** [comment] 2021-03-13 14:39
once again: does applying [this changeset](https://github.com/quodlibet/quodlibet/pull/2481/files#diff-725a1363e50790bee2c8cd9a7aff8ded) fix the issue? It does for me (tested on xfwm) but I recall vaguely that it didn't play nice on gnome-shell. If it works now, I may re-submit the pull request (or someone else can do it instead).

**Comment by Meriipu** [comment] 2021-03-13 16:22
> once again: does applying [this changeset](https://github.com/quodlibet/quodlibet/pull/2481/files#diff-725a1363e50790bee2c8cd9a7aff8ded) fix the issue? It does for me (tested on xfwm) but I recall vaguely that it didn't play nice on gnome-shell. If it works now, I may re-submit the pull request (or someone else can do it instead).

It works until I filter by something and clear the filter. Then performance drops (but it does not drop to as bad a state as the default behaviour without the changeset).

**Comment by everdred** [comment] 2021-04-10 19:40
Just tried the changeset and can confirm I'm seeing the same issue as @Meriipu. Each individual freeze lasts for a shorter amount of time than it would without the changeset, but once the application gets into this state (such as by filtering and unfiltering) it still stays this way until I restart the application.

**Comment by CreamyCookie** [comment] 2021-04-15 11:08
another Cover Grid performance issue: #2181

**Comment by everdred** [comment] 2021-07-15 15:43
>once the application gets into this state (such as by filtering and unfiltering) it still stays this way until I restart the application

A minor correction to what I said above: I've actually noticed that once Quod Libet gets into the laggy state it _can_ be fixed without restarting: by switching to another view (like Track List) and then switching back to Cover Grid. (It's easiest to do this with keyboard shortcuts, since the menus freeze/lag along with the rest of the application.) After switching back, the application goes back to the fully performant state until the issue is triggered again.

**Comment by slosd** [comment] 2021-07-18 10:03
I've been experimenting with an implementation of cover grid using `Gtk.FlowBox` instead of `Gtk.IconView`. 

See here: https://github.com/slosd/quodlibet/commit/fad092ebdf0874c16699254c6dd8290cbf1cd03f

The performance issues I'm facing with IconView (UI freezes when scrolling, resizing the window or changing the size of the song list panel) are gone, so FlowBox seems promising to me. There are some things left to do to make it work like the current cover grid, but it should provide enough functionality to see if this is a viable alternative.

FlowBox, unlike IconView, takes a `Gio.ListModel` as a model. For this tentative implementation I wrapped the `Gtk.TreeModel` that's used for sorting and filtering and sync that with an instance of `Gio.ListStore`.

I'd greatly appreciate some feedback on this.

**Comment by everdred** [comment] 2021-07-21 01:00
@slosd From a user perspective... this is awesome and basically alleviates the various incarnations of the issue for me! When I switch to another workspace and back, the application draws in less than one second (where it might have taken 5 or 7 seconds before). If I have the view filtered with a search and then I clear the search, the view continues back to the normal performance I'd expect after a few seconds of loading, while before it would take a few seconds to load but then stay laggy forever, or until I switched views.

I just have one thing to note on performance. This is weird but it seems like the smoothness of the scrolling I get in the cover view can vary wildly... however, always in a completely predictable way. For some reason scrolling stutters more at the top of my library than the bottom, and while scrolling from top to bottom I can actually notice the "FPS" of the scrolling increase the further down I scroll. The same thing happens when scrolling from the bottom to the top (just reversed; this time performance decreases as I scroll), so it doesn't seem related to how long I've been scrolling continuously.

The issue is also consistent whether I'm dragging the scroll bar with the cursor or using my TrackPoint's mouse wheel emulation to scroll at a consistent speed. Also, I wondered if the actual content could be the issue (if I was maybe more likely to have high-res covers at the top of my library), but the performance I'm describing is always consistent whether I have cover grid view sorted by Date, Title, Rating, etc. 

Anyway, please let me know if there's more needed to help you diagnose this issue I'm seeing, and I'd also be happy to help by noting any of the

> things left to do to make it work like the current cover grid

that I come across while using it. Thank you for this @slosd!

**Comment by slosd** [comment] 2021-09-02 17:20
@everdred I have read your notes and I appreciate your feedback, I have yet to sit down and continue working on this though ;)
I don't remember seeing the behavior you describe. Choppy scrolling for me mostly seems to correlate with loading album covers. It would scroll more smoothly once all covers have been loaded.

**Comment by everdred** [comment] 2021-09-02 18:57
@slosd I thought about the possibility of cover loading being the issue, so I took care to "preload" covers by PgDown'ing  through the entire library before assessing the performance. With all the covers loaded I'm still seeing a progressively better/worse performance effect depending on location. 

I know how problematic it can be trying to describe something like this, so I took [a short screencast](https://actuallynotbad.org/nc/index.php/s/5MJnxYNwce8qzT9) that I hope demonstrates it more clearly. I wish I knew how to quantify the fps, but the difference should be apparent, especially at the extreme top/bottom.

I'm happy to help by answering questions about my setup or testing new changes, though digging into the actual code is sadly beyond my abilities.

**Comment by mareg** [comment] 2022-03-14 00:08
New user here. Banshee got removed from Fedora repository and Quod Libet looked like a good replacement.

When in cover art view scrolling is really slow, app's UI freezes frequently too + from time to time compiz crashes... my workaround is to use search function - to get the album I want to play.

Hope this gets fixed soon!

**Comment by declension** [comment] 2022-03-16 22:32
@slosd what's the latest on this - anything close to an MR or is it on hold?

**Comment by slosd** [comment] 2022-03-24 22:15
@declension I continued with my changes a while ago and I think I'm not too far off. The reason I've not submitted a PR is that I'm not happy with the structure of the new code. QuodLibet is heavily based on GtkTreeView and GtkTreeModel which are quite different from FlowBox and ListModel (Gio) w.r.t. the way updates are propagated to the UI. It might be best to just get some feedback on that in a PR.

**Comment by declension** [comment] 2022-08-18 20:41
Fixed in #4101

**Closed by declension** 2022-08-18 20:41 UTC
Labels: bug, browsers, performance
