### ISSUE TITLE
Filter panes not updating

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1841] opened 2016-02-21 00:31 UTC
When setting a filter in one of the lists, the others should update accordingly to only show a subset. Right now the update behavior is inconsistent. Some of them update, some show the whole library.
I would expect all of the lists to update according to the filters. E.g. when selecting an album I would expect to only show involved people in the left view.

Here is a video for clarification: [youtube](https://www.youtube.com/watch?v=BiyZJGerGP4)

**Comment by lazka** [comment] 2016-02-21 15:15
The filtering happens from left to right, so any selection change will only affect the panes right from it (and finally the song list)

**Comment by timpulver** [comment] 2016-02-21 15:23
That’s a strange behavior, isn’t it?

**Comment by timpulver** [comment] 2016-02-21 15:52
Why not update all lists?

**Comment by lazka** [comment] 2016-02-21 16:51
In which order?

This is how it works in foobar2k, itunes, rhythmbox,...

**Comment by timpulver** [comment] 2016-02-21 17:38
I think the order does not really matter. Every time one of the lists is changed, only the subset could be shown in the others.
I have added a list with the labels to the pane – `<organization>`. It would be great if I could browse all releases within one label.
I would expect a similar behavior as when I input a search query into the search bar, e.g. `organization=somelabel`.

But I see, this is a bit tricky…

**Comment by timpulver** [comment] 2016-02-21 17:43
A workaround would be if the order of the lists could be changed.

**Comment by lazka** [comment] 2016-02-21 17:48
> A workaround would be if the order of the lists could be changed.

That sounds good

**Comment by zsau** [comment] 2016-02-21 22:20
This is more-or-less a duplicate of #1256.

**Comment by lazka** [comment] 2016-02-22 12:52
Yeah.

**Closed by lazka** 2016-02-22 12:52 UTC
