### ISSUE TITLE
Struggling with Soundcloud integration

### ISSUE THREAD

**Issue by locness3** [quodlibet/quodlibet#3255] opened 2019-08-31 16:03 UTC
I have no soundcloud account. I'd like to search all songs by [Petit Biscuit](https://soundcloud.com/petitbiscuit). I can't seem to find docs for the query language. I've tried searching for `artist = "PETIT BISCUIT"`, `artist = "petitbiscuit"`, and `artist = "Petit Biscuit"`. None of these work, I get no results.

Can someone help me ?

**Comment by declension** [comment] 2019-09-06 08:08
I've had a look, and it is weird.

The API is not returning results _by_ that artist it seems:
https://api.soundcloud.com/tracks?oauth_token=PUT_YOUR_TOKEN_HERE&q=petit+biscuit
(look at `user.username`)

Thus there are lots by _other_ artists (mapped to`username` in Soundcloud API) with that text (eg in the title), but not _by_ Petit Biscuit according to the API. QL then correctly filters out all the results as they don't match your query for artist. It's possible that the user has a different non-obvious username perhaps?

* Completely free text search, i.e. `petit biscuit` (the API is case insensitive IIRC) bring lots of results but none by the artist it seems (see above API problem)
* Exact _string_ searches i.e.`"petit biscuit"` will only return 4 results currently, so QL is filtering these results heavily. On inspection, it seems to be choosing fields that are exactly and _fully_ matched to _petit biscuit_  which is as intended in QL, if slightly confusing (sorry)
* Workaround: use regex queries: `/petit biscuit/` will return all things matching  _petit biscuit_ but not _le biscuit est petit_ etc

**Comment by locness3** [comment] 2019-09-06 13:01
Hmmm. It didn't either work with `petit bisucit`, so yeah I will try regex.

**Comment by declension** [comment] 2020-02-09 21:33
@locness3 did you find anything more, or can we close this?

**Comment by locness3** [comment] 2020-02-12 09:04
Oh, i forgot about that :( i hope regex will work. you can close this issue

**Closed** 2020-02-12 09:07 UTC
