### ISSUE TITLE
Allow individual browser pane widths

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1863] opened 2016-02-29 11:44 UTC
<img width="450" alt="bildschirmfoto 2016-02-29 um 12 40 10" src="https://cloud.githubusercontent.com/assets/1055819/13393415/b477f112-dee1-11e5-83c6-0bd4a3b3373a.png">

Would be nice to set the width of every paned browser pane on its own by dragging the separator.

**Comment by urielz** [comment] 2016-03-02 15:03
+1 for this. There's an issue already open for this:
https://github.com/quodlibet/quodlibet/issues/1118

**Comment by declension** [comment] 2016-03-02 15:10
That was the one I was looking for. Thanks @urielz 
Closing as duplicate of #1118

**Closed by declension** 2016-03-02 15:10 UTC
Labels: enhancement
