### ISSUE TITLE
How to install (no Flatpak/Snap please!) on Debian, Ubuntu, Mint? PPA outdated.

### ISSUE THREAD

**Issue by Moonbase59** [quodlibet/quodlibet#4353] opened 2023-08-22 08:54 UTC
Steps to reproduce
------------------
See that `ppa:lazka/ppa` is 73 weeks (quodlibet) and 124 weeks old (mutagen) but Code here shows we’re at 4.7, not 4.5.0.

So where do we get the `.deb` for Debian, Ubuntu, Mint?
And is the AUR (Arch) current?

Checked the docs but it only tells about installs for 4.5.

It’s also not on PyPI.

Expected Output
---------------
Ideally: PPA and AUR being current.
Have a build chain that auto-builds these, maybe in a "stable" & "unstable" version.

It is _end users_ we’re trying to talk into using Quod Libet, after all. Flatpak and Snaps both have their deficiencies and many people don’t want/don’t have these. (Besides, Flatpak also only talks about 4.5, and Snap is forbidden here.)

Actual Output
-------------
Need some of the new features but have

- no clue how to install on Debian, Ubuntu, Mint
- end-users dependent on me who can’t/won’t build things.

Test System
-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
- Linux Mint 21.2
- Ubuntu 22.04
- Manjaro current
- Arch current

### If it's audio-related, what back-end?
—

Additional Information
----------------------
—

**Comment by declension** [comment] 2023-08-22 12:42
All available downloads are listed on [the docs downloads page](https://quodlibet.readthedocs.io/en/latest/downloads.html). We don't support PyPi as it's not intended for desktop apps.

Releases across that many systems are tricky and take time, and sadly time is in short supply. The 4.6.0 release is currently in progress, so please check back tomorrow or so.

Closing as solved, for now.

**Closed by declension** 2023-08-22 12:42 UTC
Labels: bug

**Comment by Moonbase59** [comment] 2023-08-22 17:14
Yeah, I know, things can take a while. Given that every dev donates lifetime…

Would still be sad if users wouldn’t have the chance to easily install such a wonderful piece of software that does (almost) everything right. I’ll keep looking.

**Comment by rphair** [comment] 2023-09-17 02:31
I love this program so much, but if its last available version on Ubuntu without Flatpak is `4.5.0` then it is EOL for me. 😥

**Comment by Oldbwl** [comment] 2023-09-22 16:16
I have manged to test drive 4.60 using Flatpack on a back up PC - it solves some issues I had with v 4.5.0.

Unfortunately I am not able to use the Flatpack on my Main PC. The PPA is still at v 4.5.0, With this change? If not any chance of a .deb package>

**Comment by afontenot** [comment] 2023-09-22 17:34
Maybe this is a clueless Arch user talking, but what's wrong with plain-old `sudo apt install quodlibet` for most users in this situation?

 * Every Ubuntu version after the last LTS has [the previous version of Quod Libet](https://packages.ubuntu.com/kinetic/quodlibet) (4.5.0) available. Given that this was the *current* version until only one month ago, I don't see an issue here, or why a PPA would even be necessary in this case.
 * Looking at the package files, it appears to be a traditional install and not involve Flatpack or Snap.
 * Usually when using a periodically-releasing distribution like Ubuntu, software running slightly behind the latest upstream is considered a feature, not a bug. Backports shouldn't be blindly installed without a good reason. Even if a backport is really needed here, it's worth pointing out that lazka/ppa was *current* (had the latest release) on the day this bug was filed. 4.6.0 will probably happen soon enough. So if you really do need a backport, this will probably get sorted.

For what it's worth Arch Linux has the latest stable version (4.6.0) in the repos, no AUR required. Everything seems "working as intended" to me, as Arch is a rolling release that tracks close to upstream, and the next Ubuntu LTS will probably have 4.6.0 in its repos.

**Comment by rphair** [comment] 2023-09-23 02:07
@afontenot - TL:DR because `4.5.0` is buggy and we can't test (yet) for the presence of bugs in the latest (Flatpak) version.

Example: one that's killing me particularly is that it chooses quite often to duplicate all items in a playlist: these are now XML files so they can't be easily edited nor the source files even checked to see where the duplicates are coming from.  It's the kind of thing I'd submit an issue for on GitHub (if not already) but that doesn't make sense when _we can't test for the existence of the same problem on the up-to-date version_.  And many Linux users, including our own user base, would be unwilling and/or unable to use Snap / Flatpak to get the latest version.
