### ISSUE TITLE
Cover Grid: albums should have a context menu

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2178] opened 2017-01-01 13:23 UTC
I really like the new Cover Grid Browser, but one important thing it's missing is the context menu when right clicking on an album cover.

**Comment by declension** [comment] 2017-01-05 08:51
Is this a duplicate of #2110 (which works for me) ?

**Comment by urielz** [comment] 2017-01-05 17:33
Didn't realize this was implement already. Working fine on 3.8.0 mac version.

**Comment by CreamyCookie** [comment] 2017-01-13 10:08
@Hunter16g Just for confirmation because you also added a thumb up: You also don't have a context menu in the Cover Grid browser, correct? If I may ask, which operating system are you using?

**Comment by Hunter16g** [comment] 2017-01-14 09:55
Debian 7
Quodlibet 3.8.0
Python: 2.7.9
Mutagen: 1.36
GTK+: 3.14.5 (X11)
PyGObject: 3.14.0
GStreamer: 1.4.4.0


But I'm not sure https://github.com/quodlibet/quodlibet/issues/2110 and this issue are about the same problem. I do have the context menu on individual songs, but not on albums.

**Comment by CreamyCookie** [comment] 2017-01-14 14:42
@Hunter16g Same here. True, it's #2110. But the fix, which is part of 3.8.0 AFAICS, doesn't seem to work everywhere, which is odd, because I don't see anything in there which is system specific. Maybe @darthoctopus who did the fix has an idea.

**Comment by darthoctopus** [comment] 2017-01-14 14:59
This works for me:

![workspace 1_003](https://cloud.githubusercontent.com/assets/5761408/21955769/93662bce-da3f-11e6-8860-70937fcba0eb.png)

For reference I'm using Fedora 25 with GTK 3.22 (X11) and running quodlibet on python 3.5.2.

Also, since GtkIconView doesn't have a context menu event handler, what's really happening is that we're consuming click events that aren't otherwise used for selection actions (so you won't get context menus with the menu key, for example). I suspect this might also not be kosher for some use cases.

**Comment by darthoctopus** [comment] 2017-01-14 15:31
I've put together a new PR (#2197). Try that and see if it fixes your issue?

**Comment by CreamyCookie** [comment] 2017-01-14 15:38
Thanks @darthoctopus for the info and the PR. I'll comment there.

**Closed** 2017-01-15 10:17 UTC
