### ISSUE TITLE
Issues with embedded USLT lyrics

### ISSUE THREAD

**Issue by gypsyhut** [quodlibet/quodlibet#2988] opened 2018-10-04 01:37 UTC
_Originally posted by @dannn-o in https://github.com/quodlibet/quodlibet/issues/1628#issuecomment-272671850_

**Comment by gypsyhut** [comment] 2018-10-04 01:48
There are multiple issues with USLT lyrics tag support in quodlibet:

1. Right Click -> Information (Or CTRL-I) doesn't display USLT lyrics in the "Lyrics" tab. The song has lyrics and is visible in other programs.
2. Enabled "View Lyrics" plugin. But View Lyrics pane doesn't display USLT lyrics. It shows "No lyrics found for AUD-20180609-WA0055.mp3"
3. Edit Lyrics button on view lyrics pane works, but seems to be storing every line of lyrics into a separate lyrics field! This must be avoided.
4. The above behaviour is seen in both windows and linux with quodlibet version 4.1.0

Additional feature request: Is it possible to add edit lyrics tab in "Edit Tags" view which opens with "Alt-Enter" ( Right Click - Edit  Tags)

**Comment by frestr** [comment] 2018-10-06 15:46
> Right Click -> Information (Or CTRL-I) doesn't display USLT lyrics in the "Lyrics" tab. The song has lyrics and is visible in other programs.

Is the "lyrics" tag present in the "Edit tags" window?

Also, could you post the output of `mid3v2 -l` on the mp3 file?

**Comment by gypsyhut** [comment] 2018-10-09 07:30
1. The "lyrics" tag is not present in the "Edit Tags" window. I can only see the tags - title, artist, artist, album, composer, date, performer

2. Here is the output of mid3v2 -l. Please note that the content is not in english, but they are all valid unicode encoded text.

IDv2 tag info for MyMusic/Pattupetty Songs/Completed/AUD-20180609-WA0055.mp3
APIC=other,  (image/png, 125756 bytes)
TALB=അപ്പൂപ്പൻ
TCOM=വി ദക്ഷിണാമൂർത്തി
TDRC=1976
TIT2=ഇടവപ്പാതിക്കു കുടയില്ലാതെ ഇലഞ്ഞിപ്പൂമരച്ചോട്ടില്‍
TPE1=കെ ജെ യേശുദാസ്
എൽ ആർ അഞ്ജലി
TPE2=പി ഭാസ്ക്കരൻ
TSSE=Lavf57.25.100
TXXX=compatible_brands=iso6mp41
TXXX=major_brand=dash
TXXX=minor_version=0
USLT==   =ഇടവപ്പാതിക്കു കുടയില്ലാതെ 
ഇലഞ്ഞിപ്പൂമരച്ചോട്ടില്‍ നിന്നില്ലേ നാം
ഇലഞ്ഞിപ്പൂമരച്ചോട്ടില്‍ നിന്നില്ലേ?
കുടവുമെടുത്തൊരു കാര്‍മുകില്‍ നമ്മെ
കുളിപ്പിച്ചില്ലേ പെണ്ണേ കുളിപ്പിച്ചില്ലേ?

ദാവണിത്തുമ്പുനീയഴിച്ചു നീര്‍ത്തി
പൂവേണിച്ചുരുളുകള്‍ പിഴിഞ്ഞുതോര്‍ത്തി
എന്റെകണ്ണിന്നുല്സവം മദനോത്സവം
നിന്‍ കവിളില്‍ നാണത്തിന്‍ സിന്ദൂരം സിന്ദൂരം

പൂത്തുനില്‍ക്കും പൊന്നിലഞ്ഞിനമുക്കു മേലെ
ചോര്‍ച്ചയുള്ള മുത്തുക്കുട പിടിച്ചില്ലേ
നിന്നെവാരിപ്പുണരാന്‍ നിര്‍വൃതിയിലലിയാന്‍
തെന്നലും ഞാനുമായ് കിടമത്സരം കിടമത്സരം

**Comment by frestr** [comment] 2018-10-09 20:13
Thanks. The problem was that USLT tags with non-empty language and/or description fields were ignored. It should work in master now, so feel free to check.

> Edit Lyrics button on view lyrics pane works, but seems to be storing every line of lyrics into a separate lyrics field! This must be avoided.

I will look into this.

**Comment by frestr** [comment] 2018-10-10 06:19
> I will look into this.

Ok, so the problem is that internally, multiple instances of the same tag are separated by newlines when fetched, and then converted to list entries by splitting (ref: qltk/eddittags.py L165). But this is also the case for single tags containing newlines. Thus, there is not any immediate way to differentiate the two (I suspect chaning this format will require changes in a lot of places).

Another issue is that the entries in the edit tags window are not expected to be multiline. They display just fine with newlines, but kind of breaks when you edit them.

**Comment by frestr** [comment] 2018-10-10 06:34
I made a new ticket regarding the multiple lyrics issue: #2991.

I'll close this one for now, as it should have been fixed with 03c3a0e741c79ed422b1dfb28b43e06c5bedd8d2 (please comment if that's not the case).

**Comment by gypsyhut** [comment] 2018-10-10 14:48
I don't think the issue is resolved. I still do not see the lyrics with this fix.

**Comment by gypsyhut** [comment] 2018-10-10 16:10
I can share the mp3 if you want to check it at your end. Let me know how i can upload the audio file.

**Comment by frestr** [comment] 2018-10-10 16:16
Thanks, that would be helpful. You can upload it here: https://mixtape.moe/ (note that it will be public)

**Comment by gypsyhut** [comment] 2018-10-10 16:41
Done, check here: https://my.mixtape.moe/fpelbp.mp3

**Comment by frestr** [comment] 2018-10-10 16:50
It works fine for me. Are you sure you are running the latest master version? You will need to run quodlibet from the cloned repo here from github.

**Comment by gypsyhut** [comment] 2018-10-10 16:57
Yes, i did a clone and ran quodlibet.py from the folder. Let me double check then.

**Comment by gypsyhut** [comment] 2018-10-10 17:13
It's working fine, sorry for the wrong update from my end. I was not playing the song, but expecting the lyrics to be displayed in the "View Lyrics" plugin window. Once i played the song i am able to see the lyrics. I can also see the lyrics with CTRL-i. Thanks for the fix, please close this bug.

**Closed** 2018-10-10 17:15 UTC
